# -*- coding: utf-8 -*-
import csv, re, unicodedata

def norm(s):
    s = unicodedata.normalize('NFKD', s)
    s = s.replace('’', "'").replace('‘', "'").replace('–','-').replace('—','-')
    s = s.upper()
    s = re.sub(r'[^A-Z0-9&\' ]+', ' ', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s

# ---------------------------------------------------------------
# 1. EXPLICIT OVERRIDES  (known brands, opaque names, verified cases)
#    key = normalised name  -> (Industry, Sub-Industry, Confidence)
# ---------------------------------------------------------------
OVERRIDES = {
 # --- multinationals / recognisable brands ---
 "3C METAL MIDDLE EAST": ("Oil & Gas Services","Piping & metal fabrication for oil & gas","High"),
 "AAK MIDDLE EAST LLC": ("Manufacturing - Food","Edible oils & specialty fats (AAK group)","High"),
 "A A K MIDDLE EAST LLC BRANCH": ("Manufacturing - Food","Edible oils & specialty fats (AAK group)","High"),
 "AAK INTERNATIONAL TRADING L L C": ("Food & Beverage Trading","Edible oils / fats distribution","Medium"),
 "ADANI GLOBAL FZE": ("Commodity Trading","Energy & resources trading (Adani group)","High"),
 "AFRY SWITZERLAND LTD DUBAI BRANCH": ("Engineering Consultancy","Infrastructure / energy consulting (AFRY)","High"),
 "ABU DHABI OIL COMPANY LIMITED JAPAN": ("Oil & Gas","Upstream E&P operator (ADOC)","High"),
 "ASSA ABLOY ENTRANCE SYSTEMS LLC": ("Manufacturing - Building Products","Automatic doors & entrance systems","High"),
 "ASSA ABLOY SECURITY SOLUTIONS METAL INDUSTRIES FACTORY LLC": ("Manufacturing - Building Products","Security doors & locking hardware","High"),
 "ASSA ABLOY SECURITY SOLUTIONS MIDDLE EAST": ("Manufacturing - Building Products","Locks & access control hardware","High"),
 "BULGARI MIDDLE EAST BRANCH": ("Luxury Retail","Jewellery & watches (LVMH / Bulgari)","High"),
 "BOSE UAE TRADING L L C": ("Consumer Electronics","Audio equipment distribution (Bose)","High"),
 "DEUTSCHE LUFTHANSA AG": ("Aviation","Airline","High"),
 "DENSO SALES MIDDLE EAST & NORTH AFRICA FZE": ("Automotive","OEM auto components distribution (Denso)","High"),
 "KONE MIDDLE EAST LLC": ("Elevators & Escalators","Manufacture, installation & maintenance","High"),
 "NIKON MIDDLE EAST FZE": ("Consumer Electronics","Imaging & optics distribution (Nikon)","High"),
 "RITTAL FZE": ("Manufacturing - Electrical","Enclosures & IT infrastructure (Rittal)","High"),
 "PHOENIX CONTACT MIDDLE EAST FZ LLC": ("Manufacturing - Electrical","Industrial connectivity & automation","High"),
 "GIESECKE&DEVRIENT CURRENCY TECHNOLOGY FZE": ("Technology","Currency handling & banknote systems","High"),
 "GIESECKE DEVRIENT CURRENCY TECHNOLOGY FZE": ("Technology","Currency handling & banknote systems","High"),
 "WEIR OIL & GAS": ("Oil & Gas Services","Pressure pumping equipment & aftermarket","High"),
 "ZF SERVICES MIDDLE EAST LLC": ("Automotive","Driveline & chassis components (ZF)","High"),
 "MCDONALD'S MIDDLE EAST DEVELOPMENT COMPANY DUBAI BRANCH": ("Food Service","QSR franchise development","High"),
 "CIRCLE K": ("Retail","Convenience stores / forecourt retail","High"),
 "LAGARDERE TRAVEL RETAIL UAE LLC": ("Retail","Travel & airport retail","High"),
 "SUCDEN MIDDLE EAST": ("Commodity Trading","Soft commodities - sugar & cocoa","High"),
 "B&S WORLD SUPPLY DMCC": ("Distribution","Consumer goods wholesale to travel retail","High"),
 "B&S WORLD SUPPLY FZCO": ("Distribution","Consumer goods wholesale to travel retail","High"),
 "SHAPOORJI PALLONJI INTERNATIONAL FZ": ("Construction & Contracting","Large-scale EPC contractor","High"),
 "CHINA STATE CONSTRUCTION ENGRG CORP MIDDLE EAST LLC": ("Construction & Contracting","Main contractor (CSCEC)","High"),
 "MULTIPLEX CONSTRUCTION LLC": ("Construction & Contracting","Main contractor","High"),
 "MACE INTERNATIONAL LIMITED": ("Project & Cost Consultancy","Project / programme management","High"),
 "CURRIE & BROWN": ("Project & Cost Consultancy","Quantity surveying & cost management","High"),
 "WORLEY ENGINEERING PTY LIMITED": ("Engineering Consultancy","Energy & resources EPCM (Worley)","High"),
 "WORLEY OMAN ENGINEERING LLC": ("Engineering Consultancy","Energy & resources EPCM (Worley)","High"),
 "WORLEY WLL": ("Engineering Consultancy","Energy & resources EPCM (Worley)","High"),
 "WORLEYPARSONS CONSULTANCY & PROJECTS MANAGEMENT CO W L L": ("Engineering Consultancy","Energy & resources EPCM (Worley)","High"),
 "WORLEYPARSONS EGYPT": ("Engineering Consultancy","Energy & resources EPCM (Worley)","High"),
 "WORLEYPARSONS OMAN": ("Engineering Consultancy","Energy & resources EPCM (Worley)","High"),
 "PT ROTARY ENGINEERING INDONESIA A ROTARY COMPANY": ("Oil & Gas Services","EPC for oil & gas storage terminals","High"),
 "ROTARY ENGINEERING FUJAIRAHFZE": ("Oil & Gas Services","EPC for oil & gas storage terminals","High"),
 "HIAP SENG ENGINEERING LTD FZE": ("Oil & Gas Services","Plant maintenance & fabrication","High"),
 "RED SEA HOUSING SERVICES COMPANY FZE": ("Manufacturing - Modular Buildings","Modular / portable accommodation","High"),
 "STAHL CRANE SYSTEMS FZE": ("Manufacturing - Machinery","Hoists & crane components","High"),
 "PEIKKO GULF LLC": ("Manufacturing - Building Products","Concrete connection technology","High"),
 "LATICRETE MIDDLE EAST LLC": ("Manufacturing - Building Products","Tile adhesives, grouts & mortars","High"),
 "MASAFI CO L L C": ("Manufacturing - Food & Beverage","Bottled water & beverages","High"),
 "MALABAR GOLD L L C": ("Jewellery & Precious Metals","Gold & jewellery retail","High"),
 "EMIRATES GOLD DMCC": ("Jewellery & Precious Metals","Gold refining & bullion","High"),
 "EMIRATES GOLD FZCO": ("Jewellery & Precious Metals","Gold refining & bullion","High"),
 "AL ETIHAD GOLD REFINERY DMCC": ("Jewellery & Precious Metals","Gold refining","High"),
 "KALOTI JEWELLERY INTERNATIONAL DMCC": ("Jewellery & Precious Metals","Precious metals & jewellery","High"),
 "MTM & O GOLD REFINERY DMCC": ("Jewellery & Precious Metals","Gold refining","High"),
 "KIBSONS INTERNATIONAL L L C": ("Fresh Produce & Grocery","Online grocery / fresh produce distribution","High"),
 "IBSONS TRADING CO L L C": ("Fresh Produce & Grocery","Fresh produce trading (Kibsons group)","Medium"),
 "JUBAILI BROS LLC": ("Power Generation Equipment","Generators & power solutions","High"),
 "MOHEBI LOGISTICS": ("Logistics & Supply Chain","3PL, warehousing & distribution","High"),
 "AL ROSTAMANI GROUP": ("Diversified Group","Automotive, construction, retail & finance","High"),
 "AZIZI INVESTMENTS": ("Real Estate","Property development","High"),
 "RAK PROPERTIES CO PJSC": ("Real Estate","Master developer (listed)","High"),
 "SAQR PORT AUTHORITY": ("Ports & Terminals","Bulk port operations","High"),
 "RAK PORTS SUPPLY CHAIN SOLUTIONS LLC": ("Logistics & Supply Chain","Port-based supply chain services","High"),
 "NEURO SPINAL HOSPITAL": ("Healthcare","Specialty hospital - neuro & spine","High"),
 "FAKIH IVF LIMITED": ("Healthcare","Fertility / IVF clinics","High"),
 "DR MOOPENS HEALTH CARE MANAGEMENT SERVICES": ("Healthcare","Hospital & clinic group management (Aster)","High"),
 "MEDNET LLC": ("Insurance Services","Third-party health insurance administration","High"),
 "IMG THEME PARK LLC": ("Entertainment & Leisure","Indoor theme park","High"),
 "IMG BOATS L L C": ("Manufacturing - Marine","Boat building","High"),
 "ANSAR MALL": ("Retail","Hypermarket / shopping mall retail","High"),
 "SACOOR BROTHERS GROUP": ("Retail","Fashion retail chain","High"),
 "ASHLEY EMIRATES FURNITURE L L C": ("Retail","Furniture retail (Ashley franchise)","High"),
 "PAN EMIRATES HOME FURNISHINGS LLC": ("Retail","Furniture & home furnishings retail","High"),
 "DUBAI AIR WING": ("Aviation","Government VIP flight operations","High"),
 "JET AVIATION AIRSERVICES LIMITED": ("Aviation","Business aviation services & FBO","High"),
 "AVIATION SERVICES MANAGEMENT FZE": ("Aviation","Aircraft management & support services","High"),
 "UNITED NATIONS DEVELOPMENT PROGRAMME": ("Government & NGO","UN development agency","High"),
 "FATIMA BINT MUBARAK LADIES SPORTS ACADEMY": ("Sports & Recreation","Sports academy","High"),
 "THE INDIAN HIGH SCHOOL": ("Education","K-12 private school","High"),
 "AJMAN ACADEMY": ("Education","K-12 private school","High"),
 "VICTORIA INTERNATIONAL SCHOOL OF SHARJAH": ("Education","K-12 international school","High"),
 "FRENCH INTERNATIONAL PRIVATE SCHOOL SHJ L L C SP": ("Education","K-12 international school","High"),
 "WOODLEM EDUCATION": ("Education","School group","High"),
 "COVENTRY ACADEMY FOR EDUCATIONAL DEVELOPMENT": ("Education","Training & professional development","High"),
 "AZTECH TRAINING & CONSULTANCY": ("Training & Consultancy","Corporate training provider","High"),
 "GLOMACS FZ LLC": ("Training & Consultancy","Corporate training provider","High"),
 "DUNCAN & ROSS": ("HR & Recruitment","Talent consulting & recruitment","High"),
 "SEEGENE MIDDLE EAST FZE": ("Medical & Diagnostics","Molecular diagnostics (Seegene)","High"),
 "NAOS MIDDLE EAST DMCC": ("Cosmetics & Personal Care","Dermo-cosmetics (Bioderma / NAOS)","High"),
 "KAYA MIDDLE EAST DMCC": ("Healthcare","Skin & cosmetic clinics","High"),
 "GENERAL CERAMICS CO SHARJAH JSC": ("Manufacturing - Building Products","Ceramic sanitaryware & tiles","High"),
 "EMIRATES MACARONI FACTORY LLC": ("Manufacturing - Food","Pasta & macaroni production","High"),
 "SUDHIR GENSETS FZE": ("Power Generation Equipment","Diesel generating sets","High"),
 "HIMEL INTERNATIONAL FZE DELIXI": ("Manufacturing - Electrical","Low-voltage electrical products","High"),
 "FERROSTAAL EQUIPMENT SOLUTIONS FZE": ("Industrial Equipment","Industrial plant & equipment supply","High"),
 "FERROSTAAL TECHNOLOGY SOLUTIONS LLC": ("Industrial Equipment","Industrial plant & equipment supply","High"),
 "STANFORD MARINE L L C": ("Marine Services","OSV ownership & marine services","High"),
 "GMMOS GROUP INC": ("Marine Services","Ship repair & marine engineering","High"),
 "VALIANT PACIFIC LLC": ("Marine Services","Offshore & marine support services","High"),
 "CRAWFORD MIDDLE EAST LLC": ("Insurance Services","Loss adjusting & claims management","High"),
 "CLA EMIRATES CHARTERED ACCOUNTANTS AND AUDITORS LLC": ("Professional Services","Audit, tax & advisory","High"),
 "EHAF CONSULTING ENGINEERS": ("Engineering Consultancy","Design & supervision consultancy","High"),
 "JACOBS ZAMEL AND TURBAG CONSULTING ENGINEERS": ("Engineering Consultancy","Design & supervision consultancy","High"),
 "MUC MIDDLE EAST ENGINEERING CONSULTANCY": ("Engineering Consultancy","Design & supervision consultancy","High"),
 "QUALITY INTERNATIONAL CO LTD FZC": ("Manufacturing - Steel Fabrication","Heavy steel & modular fabrication","High"),
 "UNGER STEEL MIDDLE EAST FZE": ("Manufacturing - Steel Fabrication","Structural steel construction","High"),
 "UNGER STEEL FABRICATION FZE": ("Manufacturing - Steel Fabrication","Structural steel construction","High"),
 "NATIONAL ALUMINIUM & STEEL FACTORY GINCO": ("Manufacturing - Metals","Aluminium & steel products","High"),
 "GINCO CONTRACTING CO LLC": ("Construction & Contracting","Main contractor (GINCO group)","High"),
 "MINERAL CIRCLES BEARINGS FZE": ("Industrial Distribution","Bearings & power transmission","High"),
 "DICETEK LLC": ("IT Services","IT consulting & managed services","High"),
 "FACTS COMPUTER SOFTWARE HOUSE LLC": ("Software & ERP","ERP software vendor","High"),
 "DYNAMICS AXIS SOFTWARE HOUSE LLC": ("Software & ERP","Microsoft Dynamics ERP partner","High"),
 "RAMTECH SOFTWARE SOLUTIONS PRIVATE LIMITED": ("Software & ERP","Software development services","High"),
 "TRIAD SOFTWARE SERVICES": ("Software & ERP","Software development services","High"),
 "QBURST MIDDLE EAST": ("Software & ERP","Software development & digital services","High"),
 "ATOP COMPUTER SOLUTION LLC": ("IT Services","IT hardware & solutions","High"),
 "DIGITAL OFFICE LLC": ("IT Services","Office automation & IT solutions","High"),
 "NETCO NETWORK SECURITY SOLUTIONS LLC": ("IT Services","Network & cyber security solutions","High"),
 "WATERLINE IT SOLUTIONS FZE": ("IT Services","IT solutions & services","High"),
 "APTVEL GLOBAL INFORMATION TECHNOLOGIES LLC": ("IT Services","IT solutions & services","High"),
 "SUNTECH BUSINESS SOLUTIONS": ("IT Services","Business software & IT solutions","Medium"),
 "ULTIMATE BUSINESS SOLUTION LLC": ("IT Services","Business software & IT solutions","Medium"),
 "DNA DATA & ANALYTICS SOLUTIONS": ("IT Services","Data & analytics consulting","High"),
 "TAQNIAT INTELLIGENT SOLUTIONS": ("IT Services","Technology solutions integrator","Medium"),
 "SMART MOBILE SOLUTIONS": ("IT Services","Mobile technology solutions","Medium"),
 "C4C TECHNOLOGIES LLC": ("IT Services","Technology solutions","Medium"),
 "ROAMWORKS TRADING LLC": ("IoT & Telematics","Asset tracking & fleet telematics","High"),
 "HUTCHINSON TELECOM FZCO": ("Telecommunications","Telecom equipment & services","Medium"),
 "TELEPHONY TELECOM TECHNOLOGIES": ("Telecommunications","Telecom systems & services","High"),
 "RESURGENT AV INTEGRATORS PVT LTD": ("AV & Systems Integration","Audio-visual systems integration","High"),
 "SHOWTECH SOUND LIGHTING AND SUPPORT SYSTEMS": ("AV & Systems Integration","Event sound & lighting systems","High"),
 "GRANTEQ GENERAL TRADING LLC": ("AV & Systems Integration","AV distribution & integration","High"),
 "BARAJOUN ENTERTAINMENT FZ LLC": ("Media & Entertainment","Film / animation production","High"),
 "CAPITAL BUSINESS CHANNEL TV FZ LLC": ("Media & Entertainment","TV broadcasting","High"),
 "AL AQARIYA GROUP REAL ESTATE TV": ("Media & Entertainment","Real estate TV / media","High"),
 "THE PRODUCTION HUB L L C": ("Media & Entertainment","Video / event production","High"),
 "EVOLUTION EVENTS LLC": ("Events & Exhibitions","Event management","High"),
 "GEAR UP EVENTS LLC": ("Events & Exhibitions","Event management","High"),
 "DUBAI MARINE BEACH RESORT AND SPA": ("Hospitality","Hotel & resort","High"),
 "THE H HOTEL LLC": ("Hospitality","Hotel","High"),
 "THE IMPERIAL SUITES HOTEL": ("Hospitality","Hotel","High"),
 "BILLIONAIRE MANSION DUBAI": ("Hospitality","Restaurant & nightlife venue","High"),
 "GLOBAL HOSPITALITY LTD": ("Hospitality","Hospitality management","High"),
 "GLOBAL INCENTIVES TOURISM": ("Travel & Tourism","DMC / incentive travel","High"),
 "KHADAMAT FACILITIES MANAGEMENT LLC": ("Facilities Management","Integrated FM services","High"),
 "CONCORDIA INTERNATIONAL MIDDLE EAST FZ LLC": ("Facilities Management","Integrated FM services","High"),
 "STAR SERVICES LLC": ("HR & Recruitment","Manpower supply & outsourcing","High"),
 "STAR SERVICES OUTSOURCING CONSULTANTS LTD COMPANY": ("HR & Recruitment","Manpower outsourcing","High"),
 "SUNDUS RECRUITMENT & OUTSOURCING SERVICES LLC": ("HR & Recruitment","Recruitment & outsourcing","High"),
 "TALENT VISION COMPANY": ("HR & Recruitment","Recruitment services","High"),
 "WORKFORCE CONNEXIION LLC": ("HR & Recruitment","Manpower supply","High"),
 "OILEXEC EMPLOYMENT SOLE PROPRIETORSHIP LLC": ("HR & Recruitment","Oil & gas manpower supply","High"),
 "CORPORATE SERVICES INTERNATIONAL N V": ("Professional Services","Corporate services & outsourcing","Medium"),
 "GLOBAL INVESTMENTS NV": ("Investment & Holding","Investment holding company","Medium"),
 "EXPENZIA PTE LTD": ("Software & ERP","Spend management software","Medium"),
 "PLUTUS GLOBAL PTE LTD": ("Trading & Distribution","International trading","Low"),
 "MELDEN ADVISORY DMCC": ("Professional Services","Corporate / financial advisory","High"),
 "DEXTER CAPITAL FINANCIAL CONSULTANCY LLC": ("Financial Services","Financial consultancy","High"),
 "ICL FINCORP INVESTMENT LLC": ("Financial Services","Gold loans & NBFC services","High"),
 "COSMOS INSURANCE BROKERS LLC": ("Insurance Services","Insurance broking","High"),
 "AAA FAIR DEAL COMMERCIAL BROKER LLC": ("Financial Services","Commercial broking","Medium"),
 "BELAL KABUL BAKHTAR MONEY SERVICE PROVIDER": ("Financial Services","Money exchange & remittance","High"),
 "ALKHOORY CAPITAL INVESTMENT LLC": ("Investment & Holding","Investment holding","High"),
 "GALADARI MOTOR DRIVING CENTER LLC": ("Education","Driving school","High"),
 "IDEAL DRIVING INSTITUTE": ("Education","Driving school","High"),
 "INTERNATIONAL KNOWLEDGE CENTER": ("Education","Training centre","Medium"),
 "DUBATT BATTERY RECYCLING LLC": ("Recycling & Waste","Lead-acid battery recycling","High"),
 "NAD SHABEEB WASTE COLLECTION & TRANSPORTING": ("Recycling & Waste","Waste collection & transport","High"),
 "FEET WASTE TRANSPORTER": ("Recycling & Waste","Waste transport","Medium"),
 "INTEGRATED GREEN RESOURCES L L C": ("Recycling & Waste","Waste management & recycling","High"),
 "HADIR PROJECTS & ENVIRONMENT SYSTEMS L L C": ("Environmental Services","Environmental / water treatment projects","High"),
 "DOHA QUARRY LLC": ("Mining & Quarrying","Aggregates & quarry products","High"),
 "UNITED QUARRIES": ("Mining & Quarrying","Aggregates & quarry products","High"),
 "TAWOOS AGRICULTURE UAE LLC": ("Agriculture","Agricultural production & services","High"),
 "TWAM AGRICULTURE": ("Agriculture","Agricultural production","Medium"),
 "MAHASEEL PRODUCE": ("Fresh Produce & Grocery","Fresh produce supply","High"),
 "MAHASEEL INVESTMENT IN COMMERCIAL ENTERPRISES & MANAGEMENT L L C": ("Investment & Holding","Investment & management company","Medium"),
 "BLACK TULIP FRESH PRODUCE LLC": ("Fresh Produce & Grocery","Fresh produce distribution","High"),
 "EPICURE CATERING HEALTH FACTORY": ("Food Service","Catering & meal production","High"),
 "APEX ALWATANIAH CATERING SERVICE SOLE PROPRIETORSHIP LLC": ("Food Service","Contract catering","High"),
 "MISTER BAKER LLC": ("Manufacturing - Food","Bakery & cakes","High"),
 "EUROPEAN BAKERY": ("Manufacturing - Food","Bakery","High"),
 "EUROPEAN BAKERY BR OF AW BIN SHABIB INVESTEMENT LLC": ("Manufacturing - Food","Bakery","High"),
 "GULF PASTRY LLC": ("Manufacturing - Food","Bakery & pastry production","High"),
 "SWISS CHOCOLATE FACTORY LLC": ("Manufacturing - Food","Chocolate & confectionery","High"),
 "CHOCO PALACE CHOCOLATE FACTORY L L C": ("Manufacturing - Food","Chocolate & confectionery","High"),
 "COCOA PALACE SWEETS S P S L L C": ("Manufacturing - Food","Confectionery & sweets","High"),
 "JMM MEAT PROCESSING LLC": ("Manufacturing - Food","Meat processing","High"),
 "SEA WORLD FISH PROCESSING LLC": ("Manufacturing - Food","Seafood processing","High"),
 "RAK FISH AND FOOD DRYING LLC": ("Manufacturing - Food","Fish & food drying","High"),
 "THE PAVILION FOOD PROCESSING LLC": ("Manufacturing - Food","Food processing","High"),
 "MUNCHERIE ORGANIC FOOD MANUFACTURING LLC": ("Manufacturing - Food","Organic food production","High"),
 "MASHARIF FOOD INDUSTRIES ONE PERSON COMPANY LLC": ("Manufacturing - Food","Food production","High"),
 "ALRABYA LEBANESE FACTORY CHEESE MANUFACTURING LLC SOLE PROPRIETORSHIP": ("Manufacturing - Food","Cheese & dairy production","High"),
 "AL QOTUF AL MOBRAKA DATES FACTORY LLC": ("Manufacturing - Food","Dates processing & packing","High"),
 "AL YANBOU FOOD INDUSTRIES CO LLC": ("Manufacturing - Food","Food production","High"),
 "ALI GHOLAMI FOOD INDUSTRIES LLC": ("Manufacturing - Food","Food production","High"),
 "AL JAWDHA FOODS LLC": ("Food & Beverage Trading","Foodstuff supply","Medium"),
 "ITALFOOD FZ LLC": ("Food & Beverage Trading","Italian food distribution","High"),
 "GUSTO VERO FOODSTUFF FZ LLC": ("Food & Beverage Trading","Specialty food distribution","High"),
 "VENDOME TEA DMCC": ("Food & Beverage Trading","Tea trading & branding","High"),
 "TRITON FOODS LLC": ("Food & Beverage Trading","Foodstuff distribution","Medium"),
 "AL RAWDAH GREEN SWEET WATER": ("Manufacturing - Food & Beverage","Drinking water supply","High"),
 "HOLA DELIGHTS JUICES LLC": ("Manufacturing - Food & Beverage","Juices & beverages","High"),
 "A G K REFRESHMENTS L L C": ("Food & Beverage Trading","Beverages & refreshments","Medium"),
 "GALLERY FOODS & BEVERAGES LLC": ("Food & Beverage Trading","Food & beverage supply","Medium"),
 "SAMA ALKHAIR FOOD & BEVERAGES TRADING CO LLC": ("Food & Beverage Trading","Food & beverage trading","High"),
 "AFRAH TOBACCO & CIGARETTES FACTORY FZ LLC": ("Manufacturing - Tobacco","Cigarette manufacturing","High"),
 "AL MOKHTAR TOBACCO MANUFACTURING & TRADING FZ LLC": ("Manufacturing - Tobacco","Tobacco manufacturing & trading","High"),
 "RHEIN TOBACCO INTERNATIONAL FZ LLC": ("Manufacturing - Tobacco","Tobacco trading & manufacturing","High"),
 "ARABIAN INDUSTRIAL GASES CO": ("Manufacturing - Chemicals","Industrial gases","High"),
 "BADER GAS SUPPLY EST": ("Industrial Distribution","Industrial & LPG gas supply","High"),
 "GLOBE CHEMICALS COMPANY LLC": ("Chemicals Distribution","Industrial chemicals trading","High"),
 "SREE CHEMTECH FZE": ("Chemicals Distribution","Specialty chemicals trading","High"),
 "FINOTECH SILICONE CHEMICALS LLC": ("Manufacturing - Chemicals","Silicones & sealants","High"),
 "KANZ CHEMICAL IND LLC": ("Manufacturing - Chemicals","Chemical products","High"),
 "AL GHAITH CHEMICAL INDUSTRIES LLC": ("Manufacturing - Chemicals","Chemical products","High"),
 "ARPE LUBRICANTS": ("Manufacturing - Chemicals","Lubricants & oils","High"),
 "PRIME PETROLEUM FZC": ("Oil & Gas","Petroleum products trading","High"),
 "PETROKAN DMCC": ("Oil & Gas","Petroleum products trading","High"),
 "PETROFOSSIL HOLDING FZC": ("Oil & Gas","Petroleum / energy holding","Medium"),
 "PETRONA GULF DWC LLC": ("Oil & Gas Services","Oilfield services & supply","High"),
 "PETRONA GULF PIPING LLC": ("Oil & Gas Services","Piping & fabrication","High"),
 "PST PIONEER OILFIELD EQUIPMENT MANUFACTURING LTD": ("Oil & Gas Services","Oilfield equipment manufacturing","High"),
 "UNI ARAB ENGINEERING & OILFIELD SERVICES": ("Oil & Gas Services","Oilfield engineering services","High"),
 "BLUE HORIZON SERVICES & OIL FIELD MAINTENANCE LLC": ("Oil & Gas Services","Oilfield maintenance services","High"),
 "EMIRATES SPECIALIZED CONTRACTING & OILFIELD SERVICES L L C": ("Oil & Gas Services","Oilfield contracting","High"),
 "STREAM ENERGY DEVELOPMENT SOLE PROPRIETORSHIP L L C": ("Energy","Energy project development","Medium"),
 "NEON ENERGY GROUP": ("Energy","Energy solutions","Medium"),
 "FORTUNE ENGINEERING & ENERGY SERVICES L L C": ("Oil & Gas Services","Engineering & energy services","High"),
 "FORTUNE ENGINEERING & ENERGY SERVICES SAUDI LTD": ("Oil & Gas Services","Engineering & energy services","High"),
 "AL MAKAMIN COMMERCIAL PROJECTS LLC": ("Oil & Gas Services","Oilfield support & projects","Medium"),
 "EASTERN MORRIS CRANES CO LTD": ("Industrial Equipment","Cranes & lifting equipment","High"),
 "PVE CRANES MIDDLE EAST LLC": ("Industrial Equipment","Cranes & piling equipment","High"),
 "EMIRATES CRANES TRADING LLC": ("Industrial Equipment","Cranes & lifting equipment","High"),
 "CENTURY EQUIPMENT COMPANY LLC": ("Industrial Equipment","Equipment supply","Medium"),
 "ITR MIDDLE EAST FZCO": ("Industrial Equipment","Undercarriage parts for earthmoving","High"),
 "BELVEN DWC LLC": ("Industrial Distribution","Industrial valves","High"),
 "PHOENIX GLOBAL VALVE MANUFACTURING LLC": ("Manufacturing - Machinery","Industrial valves","High"),
 "CAMTECH MANUFACTURING FZCO": ("Manufacturing - Machinery","Valves & instrumentation fittings","High"),
 "MAICO GULF L L C": ("Manufacturing - HVAC","Ventilation equipment (Maico)","High"),
 "MAICO VENTILATION PVT LTD": ("Manufacturing - HVAC","Ventilation equipment","High"),
 "VTS CLIMA WLL": ("Manufacturing - HVAC","Air handling units & HVAC","High"),
 "VTS MEA AIR CONDITION TRADING CO LLC": ("HVAC Trading","Air conditioning equipment","High"),
 "AERODUCT INDUSTRIES L L C": ("Manufacturing - HVAC","Air ducting systems","High"),
 "MIDDLE EAST FUJI LLC": ("Elevators & Escalators","Lift supply & installation","High"),
 "COMFORT ELEVATORS & ESCALATORS": ("Elevators & Escalators","Lift installation & maintenance","High"),
 "YORK ELEVATORS & ESCALATORS FIXING LLC": ("Elevators & Escalators","Lift installation & maintenance","High"),
 "SOLICO FIBERGLASS FACTORY LLC": ("Manufacturing - Plastics","FRP / fiberglass products","High"),
 "AQUAPLEX FZE": ("Manufacturing - Plastics","Composite / plastic water tanks","High"),
 "AQUAPLEX TRADING WLL": ("Building Materials Trading","Water tanks & plumbing products","High"),
 "CORODEX TRADING CO LLC": ("Water Treatment","Water treatment & pumps","High"),
 "HYDROTECH LINE CONTRACTING AND WATER DISTRIBUTION LLC": ("Water Treatment","Water distribution contracting","High"),
 "AQUAPOWER CONTRACTING LLC": ("MEP & Electromechanical","Water / power contracting","High"),
 "AQUATECH LANDSCAPE & CIVIL SERVICES": ("Landscaping","Landscape & civil works","High"),
 "GHANTOOT LANDSCAPING LLC": ("Landscaping","Landscape contracting","High"),
 "PANAMERA LANDSCAPING L L C": ("Landscaping","Landscape contracting","High"),
 "PLANTA LANDSCAPING AND IRRIGATION L L C": ("Landscaping","Landscape & irrigation","High"),
 "LAWNSCAPE LLC": ("Landscaping","Landscape services","High"),
 "WOROOD INTRAFLORA LLC": ("Florist & Gifts","Flowers & gifts retail","High"),
 "DOMUS FLOWER LLC": ("Florist & Gifts","Flowers retail","High"),
 "AMARA FLOWERS LLC": ("Florist & Gifts","Flowers retail","High"),
 "FRESHER FLOWERS L L C FZ": ("Florist & Gifts","Flowers wholesale","High"),
 "NATIONAL FLOWER CO LLC": ("Florist & Gifts","Flowers wholesale","High"),
 "FOREVER ROSE LONDON": ("Florist & Gifts","Preserved roses & luxury gifts","High"),
 "ROSE PARIS FLOWERS & GIFTS ONE PERSON COMPANY LLC": ("Florist & Gifts","Flowers & gifts retail","High"),
 "SILVER ROCK FRAMING GALLERY LLC": ("Retail","Art framing & gallery","High"),
 "RIOT ART": ("Media & Entertainment","Art / creative studio","Low"),
 "FOTOFUN COLOR LAB": ("Retail","Photo lab & printing services","High"),
 "THE LEATHER DOCTOR": ("Repair Services","Leather & upholstery repair","High"),
 "PHYSIO-ART": ("Healthcare","Physiotherapy clinic","High"),
 "360 WELLNESS": ("Healthcare","Wellness & fitness services","Medium"),
 "ALL FIT LIFESTYLE COACHING CO LLC": ("Health & Fitness","Fitness coaching","High"),
 "JURASSIC TECHNOLOGIES L L C KO GYM": ("Health & Fitness","Gym / fitness centre","High"),
 "BACK & PRO DMCC": ("Health & Fitness","Sports & physio products","Medium"),
 "3 NVENEERS DENTAL LABORATORY": ("Healthcare","Dental laboratory","High"),
 "SPECTRUM HEARTS THERAPEUTIC CENTER": ("Healthcare","Therapy & rehabilitation centre","High"),
 "ADAM & EVE SPECIALIZED MEDICAL CENTRE LLC": ("Healthcare","Medical centre","High"),
 "CURE ARENA MEDICAL CENTER LLC": ("Healthcare","Medical centre","High"),
 "AL TOMOH AL MUTAMAYIZ MEDICAL CENTER LLC": ("Healthcare","Medical centre","High"),
 "INTERNATIONAL RADIOLOGY & DIAGNOSTIC SERVICES CENTRE LLC RAK BRANCH": ("Healthcare","Diagnostic imaging centre","High"),
 "LIFE HOME HEALTHCARE LLC": ("Healthcare","Home healthcare services","High"),
 "FAITH HEALTHCARE MANAGEMENT LLC": ("Healthcare","Healthcare management","High"),
 "SAAS HEALTH CARE INVESTMENT L L C": ("Healthcare","Healthcare investment & operations","Medium"),
 "BLUE OCEAN HEALTH FZ LLC": ("Healthcare","Health services / products","Medium"),
 "AL REEM HOSPICO CO LLC": ("Medical Supplies","Hospital supplies","Medium"),
 "OSUS AL-IBDAA MEDICAL COMPANY": ("Medical Supplies","Medical equipment & supplies","High"),
 "MASAR MEDICAL CO": ("Medical Supplies","Medical equipment & supplies","High"),
 "HEALTHCARE SCIENTIFIC SUPPLIES SPC": ("Medical Supplies","Scientific & medical supplies","High"),
 "AGILE MEDICAL SUPPLIES PVT LTD": ("Medical Supplies","Medical supplies","High"),
 "PHARMAETHICS MEDICAL SUPPLIES LLC": ("Medical Supplies","Medical supplies","High"),
 "BIOTECHNOLOGY INTERNATIONAL CO L L C": ("Medical & Diagnostics","Lab & diagnostics equipment","High"),
 "BIOPHARMA MIDDLE EAST & AFRICA": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "UNITED COMPANY VETERINARY MEDICINES IND L L C": ("Pharmaceuticals","Veterinary medicines manufacturing","High"),
 "LUTFI OPTICAL CENTER LLC": ("Retail","Optical / eyewear retail","High"),
 "LUTFI TRADING LLC": ("Trading & Distribution","Eyewear & optical products trading","Medium"),
 "SWISS WATCH HOUSE L L C": ("Luxury Retail","Watch retail","High"),
 "SWISS WATCH GROUP LLC": ("Luxury Retail","Watch retail & distribution","High"),
 "BLACKBOX GLOBAL LUXURY GROUP DMCC": ("Luxury Retail","Luxury goods trading","High"),
 "LUXURIA MIDDLE EAST DMCC": ("Luxury Retail","Luxury goods trading","High"),
 "SKY JEWELLERY": ("Jewellery & Precious Metals","Jewellery retail","High"),
 "KANZ JEWELS LLC": ("Jewellery & Precious Metals","Jewellery retail","High"),
 "AL BAHRAIN JEWELLERS LLC": ("Jewellery & Precious Metals","Jewellery retail","High"),
 "ARTS AND GEMS L L C": ("Jewellery & Precious Metals","Gems & jewellery","High"),
 "AYOUB MOOSA GOLDSMITH EQUIP TR L L C": ("Industrial Distribution","Goldsmith tools & equipment","High"),
 "GEEBEE GARMENTS FZE": ("Manufacturing - Textiles","Garment manufacturing","High"),
 "IMPERIAL GARMENTS INDUSTRY FZE": ("Manufacturing - Textiles","Garment manufacturing","High"),
 "SNOWHITE GARMENTS L L C": ("Manufacturing - Textiles","Uniforms & workwear","High"),
 "KAYAN SEWING LLC": ("Manufacturing - Textiles","Garment / sewing production","High"),
 "JIADI INTERNATIONAL READYMADE GARMENTS": ("Textiles & Apparel Trading","Readymade garments trading","High"),
 "SKY CITY READYMADE GARMENTS TRADING LLC": ("Textiles & Apparel Trading","Readymade garments trading","High"),
 "DIVA ABAYA COUTURE GARMENTS TRADING LLC": ("Textiles & Apparel Trading","Abaya & couture retail","High"),
 "HANOX FASHION RETAIL LLC": ("Retail","Fashion retail","High"),
 "NEW FASHION GALLERY LLC": ("Retail","Fashion retail","High"),
 "NEW FASHION TRACK ENTERPRISES LLC": ("Textiles & Apparel Trading","Fashion trading","Medium"),
 "SPOT SHOES TRADING": ("Textiles & Apparel Trading","Footwear trading","High"),
 "ITALIAN FOOTWEAR SOLUTION LLC": ("Textiles & Apparel Trading","Footwear supply","High"),
 "HANDLOOM HOUSE HEAD OFFICE LLC": ("Retail","Textile & handloom retail","High"),
 "BRU TEXTILES NV": ("Textiles & Apparel Trading","Furnishing fabrics","High"),
 "BRU MIDDLE EAST FZE": ("Textiles & Apparel Trading","Furnishing fabrics","High"),
 "FABRIC LIBRARY FZCO": ("Textiles & Apparel Trading","Furnishing fabrics","High"),
 "TOGETHER TEXTILES CHINA": ("Textiles & Apparel Trading","Textile sourcing & supply","High"),
 "VINIRMA TEXTILES EXPORTS PRIVATE LIMITED": ("Textiles & Apparel Trading","Textile export","High"),
 "FIVE STAR TEXTILES L L C": ("Textiles & Apparel Trading","Textile trading","High"),
 "NASEEB TEXTILES LLC": ("Textiles & Apparel Trading","Textile trading","High"),
 "SILKLAND TRADING L L C": ("Textiles & Apparel Trading","Furnishing fabrics & textiles","High"),
 "SILK LAND TRADING FZCO": ("Textiles & Apparel Trading","Furnishing fabrics & textiles","High"),
 "SILK LAND STAR TRADING L L C": ("Textiles & Apparel Trading","Furnishing fabrics & textiles","High"),
 "SILKLAND FURNISHING PRIVATE LTD BANGALORE": ("Textiles & Apparel Trading","Furnishing fabrics","High"),
 "SILVER ARCADE LINEN LLC": ("Textiles & Apparel Trading","Linen & home textiles","High"),
 "FAMILY TEX CURTAINS FABRICS TRADING LLC": ("Textiles & Apparel Trading","Curtains & fabrics","High"),
 "FINESSE FABRICS & FURNITURE TRADING": ("Furniture & Interiors","Fabrics & furniture trading","High"),
 "FLOORTEX FURNISHINGS": ("Furniture & Interiors","Flooring & furnishings","High"),
 "WOODFLOORS MIDDLE EAST L L C": ("Furniture & Interiors","Wood flooring supply","High"),
 "NIC GALLERY CARPETS & HOME DECOR LLC": ("Furniture & Interiors","Carpets & home decor","High"),
 "KNOT HOME DECORATION MATERIALS TRADING LLC": ("Furniture & Interiors","Home decor materials","High"),
 "DUBAI FURNITURE MANUFACTURING LLC": ("Manufacturing - Furniture","Furniture production","High"),
 "MARVELOUS DESIGN FURNITURE": ("Manufacturing - Furniture","Custom furniture","High"),
 "MARVELOUS DESIGN FURNITURE L L C S P C": ("Manufacturing - Furniture","Custom furniture","High"),
 "MANSOUR BAYEGAN FURNITURES LLC": ("Furniture & Interiors","Furniture trading","High"),
 "ESMAEIL MOHD BAYGAN FURNITURE TRDG LLC": ("Furniture & Interiors","Furniture trading","High"),
 "HYSSNA CARPENTRY": ("Fit-Out & Joinery","Joinery & carpentry","High"),
 "HYSSNA INTERNATIONAL INTERIORS DESIGN LLC": ("Fit-Out & Joinery","Interior design & fit-out","High"),
 "HYSSNA INTERNATIONAL LLC": ("Fit-Out & Joinery","Interiors & joinery","High"),
 "MAPLETEC JOINERY LLC": ("Fit-Out & Joinery","Joinery & millwork","High"),
 "LA SOROGEEKA INTERIORS L L C": ("Fit-Out & Joinery","Luxury interiors & joinery","High"),
 "INTERIORS INTERNATIONAL INDUSTRIES L L C": ("Fit-Out & Joinery","Joinery & interior manufacturing","High"),
 "INTERIORS INTERNATIONAL FZCO": ("Fit-Out & Joinery","Joinery & interior manufacturing","High"),
 "VEXUS INTERIORS L L C": ("Fit-Out & Joinery","Interior fit-out","High"),
 "EVA INTERIOR FITOUTS": ("Fit-Out & Joinery","Interior fit-out","High"),
 "BCI FITOUT CONTRACTING LLC": ("Fit-Out & Joinery","Interior fit-out contracting","High"),
 "AL DHIYAFA INTERIORS LLC": ("Fit-Out & Joinery","Interior fit-out","High"),
 "TUNES INTERIOR DECORATION": ("Fit-Out & Joinery","Interior decoration","High"),
 "BRAINFREEZE INTERIOR DECORATION LLC": ("Fit-Out & Joinery","Interior decoration","High"),
 "EBONITE DECOR LLC": ("Fit-Out & Joinery","Interior decor & fit-out","High"),
 "CITY SPACE LLC": ("Fit-Out & Joinery","Interior fit-out","Medium"),
 "MS ARCHITECTURE & DESIGN": ("Architecture & Design","Architectural design","High"),
 "DRAW LINK GROUP": ("Fit-Out & Joinery","Design & fit-out contracting","High"),
 "ARAB ITALIAN MARBLES": ("Building Materials Trading","Marble & natural stone","High"),
 "UNIMAR MARBLE FACTORY": ("Manufacturing - Building Products","Marble processing","High"),
 "SULTHAN STONES LLC": ("Building Materials Trading","Natural stone supply","High"),
 "ALCON CONCRETE PRODUCTS L L C": ("Manufacturing - Building Products","Precast concrete products","High"),
 "SAAD PRECAST LLC": ("Manufacturing - Building Products","Precast concrete","High"),
 "MIX DESIGN CEMENT PRODUCT TRADING": ("Building Materials Trading","Cement products","High"),
 "ABU DHABI PIPE FACTORY": ("Manufacturing - Building Products","Pipes manufacturing","High"),
 "ALINCO PIPE SUPPLY FZE": ("Industrial Distribution","Pipes & fittings supply","High"),
 "GALVANIZING SERVICES L L C": ("Metal Treatment Services","Hot-dip galvanizing","High"),
 "PROCOAT STEEL SOLUTIONS LLC": ("Metal Treatment Services","Steel coating & treatment","High"),
 "RHINO STEEL INDUSTRIES & COATING LLC": ("Manufacturing - Steel Fabrication","Steel products & coating","High"),
 "EURO BLAST MIDDLE EAST L L C": ("Metal Treatment Services","Blasting & painting services","High"),
 "CLEAN BLAST INTERNATIONAL L L C": ("Metal Treatment Services","Blasting & surface preparation","High"),
 "SPEED BLAST TRADING LLC": ("Industrial Distribution","Blasting equipment & abrasives","High"),
 "EMIRATES NATIONAL COPPER FACTORY LLC": ("Manufacturing - Metals","Copper products","High"),
 "AL HAMY METALS FACTORY LLC": ("Manufacturing - Metals","Metal products","High"),
 "FENGO METALS ENGINEERING": ("Manufacturing - Metals","Metal fabrication","High"),
 "TEE DEE METALS LLC": ("Manufacturing - Metals","Metal products","Medium"),
 "TEE DEE METAL SOLUTIONS FZE": ("Manufacturing - Metals","Metal products","Medium"),
 "TEE DEE TECHNOLOGIES LLC": ("Trading & Distribution","Technical products trading","Low"),
 "TEE DEE INTERNATIONAL FZE": ("Trading & Distribution","General trading","Low"),
 "TEE DEE TRADING L L C": ("Trading & Distribution","General trading","Low"),
 "CORE METAL LLC": ("Manufacturing - Metals","Metal fabrication","Medium"),
 "BEST METAL STEEL TRADING LLC": ("Steel & Metals Trading","Steel trading","High"),
 "AL RAS STEEL TRADING FZCO": ("Steel & Metals Trading","Steel trading","High"),
 "MK GLOBAL STEEL & TIMBER TRADING FZCO": ("Steel & Metals Trading","Steel & timber trading","High"),
 "FIRST SOURCE STEELWARE TRADING LLC": ("Steel & Metals Trading","Steel products trading","High"),
 "SKY STEEL SYSTEMS LLC": ("Manufacturing - Steel Fabrication","Steel structures","High"),
 "INVENTION STEEL INDUSTRIES LLC": ("Manufacturing - Steel Fabrication","Steel fabrication","High"),
 "FERROFAB FZE": ("Manufacturing - Steel Fabrication","Steel fabrication","High"),
 "QUALITY FABRICATION FZE": ("Manufacturing - Steel Fabrication","Steel fabrication","High"),
 "ALPHA METAL CONST IND LLC": ("Manufacturing - Steel Fabrication","Metal construction industries","High"),
 "PERFECTION METAL INDUSTRIES LLC": ("Manufacturing - Metals","Metal products","High"),
 "WHITE ALUMINIUM COMPANY LLC": ("Manufacturing - Building Products","Aluminium & glass facades","High"),
 "CORNISH ARABIAN ALUMINIUM FACTORY LLC": ("Manufacturing - Building Products","Aluminium products","High"),
 "ASHBILIA ALUMINIUM AND GLASS LLC": ("Manufacturing - Building Products","Aluminium & glass works","High"),
 "GLAZE SERVICES LLC": ("Manufacturing - Building Products","Glass & glazing services","High"),
 "ARKAN SHADE SYSTEMS LLC": ("Manufacturing - Building Products","Shade structures & tensile","High"),
 "ROOFINGS MIDDLE EAST FZC": ("Manufacturing - Building Products","Roofing systems","High"),
 "GREENTECH THERMAL INSULATION PRODUCTS MANUFACTURING LLC": ("Manufacturing - Building Products","Thermal insulation products","High"),
 "SMART INSULATION FINISHING SYSTEMS LLC": ("Construction Services","Insulation & finishing systems","High"),
 "ISOFOAM ENGINEERING L L C": ("Construction Services","Insulation systems","High"),
 "WATER SEAL INSULATION MATERIAL CONTRACTING COMPANY LLC": ("Construction Services","Waterproofing & insulation","High"),
 "EUROPE STRONG FORCE POST TENSIONING LLC": ("Construction Services","Post-tensioning specialist","High"),
 "RAPID IMPACT COMPACTION CONTRACTING L L C": ("Construction Services","Ground improvement","High"),
 "T M F EURO FOUNDATIONS L L C": ("Construction Services","Piling & foundations","High"),
 "ABN SCAFFOLDING LLC": ("Construction Services","Scaffolding supply & erection","High"),
 "APEX SCAFFOLDING LLC": ("Construction Services","Scaffolding supply & erection","High"),
 "AL MUBDEE SCAFFOLDING LLC": ("Construction Services","Scaffolding","High"),
 "STANDARD ACCESS SCAFFOLDING CONTRACTING LLC": ("Construction Services","Scaffolding & access","High"),
 "FIRE TECH FIRE FIGHTING LLC": ("Fire & Safety","Fire protection systems","High"),
 "LOTO SAFETY REQUISITES TRADING LLC": ("Fire & Safety","Safety equipment supply","High"),
 "MMJ SECURITY AND SAFETY": ("Security Services","Security & safety systems","High"),
 "MAGNUM SECURITY SERVICES": ("Security Services","Manned guarding","High"),
 "FIRST SECURITY GROUP LLC": ("Security Services","Manned guarding & systems","High"),
 "ENFORCE SECURITY SERVICE LLC": ("Security Services","Manned guarding","High"),
 "STAR SECURITY SERVICES LLC": ("Security Services","Manned guarding","High"),
 "IWATCH SECURITY SYSTEMS LLC": ("Security Systems","CCTV & security systems","High"),
 "HARROW SECURITY VEHICLES LLC": ("Manufacturing - Automotive","Armoured & security vehicles","High"),
 "HARROW VEHICLES MODIFICATIONS CO LTD": ("Manufacturing - Automotive","Vehicle modification & armouring","High"),
 "RIDA MIDDLE EAST VEHICLE BODIES MANUFACTURING LLC": ("Manufacturing - Automotive","Vehicle body building","High"),
 "RIDA MIDDLE EAST GENERAL TRADING FZCO": ("Trading & Distribution","General trading","Medium"),
 "ADVANCED EXPEDITION VEHICLES": ("Manufacturing - Automotive","Specialist vehicle conversion","High"),
 "PX TAC MILITARY EQUIPMENT TRADING COMPANY LLC": ("Defence & Security Supply","Military & tactical equipment","High"),
 "F1RST MOTORS L L C": ("Automotive Retail","Luxury & performance car dealership","High"),
 "ALLIED MOTORS TRADING FZCO": ("Automotive Retail","Vehicle trading","High"),
 "ALLIED MOTORS TRADING FZCO BRANCH": ("Automotive Retail","Vehicle trading","High"),
 "AL SHAALI MOTO TRADING LLC": ("Automotive Retail","Motorcycle & marine trading","High"),
 "STAR X AUTO TRADE FZCO": ("Automotive Retail","Vehicle trading","High"),
 "AG AUTO TRADING L L C": ("Automotive Retail","Vehicle trading","Medium"),
 "AUTO VISION TRADING FZCO": ("Automotive Parts Trading","Auto parts trading","Medium"),
 "JOHN DIESEL": ("Automotive Parts Trading","Diesel engine parts & service","High"),
 "ALEX RENNER MOTORS GARAGE LLC": ("Automotive Services","Vehicle repair garage","High"),
 "EXTREME PERFORMANCE GARAGE LLC": ("Automotive Services","Performance vehicle workshop","High"),
 "RAVON OFF ROAD PERFORMANCE AUTO REPAIRING GARAGE LLC": ("Automotive Services","Vehicle repair garage","High"),
 "STATUS 67 AUTO REPAIR LLC": ("Automotive Services","Vehicle repair garage","High"),
 "TEAM TWENTY ONE AUTO REPAIRING": ("Automotive Services","Vehicle repair garage","High"),
 "OTTOKRAFTOR VEHICLES SERVICES CO LLC": ("Automotive Services","Vehicle services","High"),
 "ALIF AUTO CARE LLC": ("Automotive Services","Vehicle care & servicing","High"),
 "DIAL A BATTERY AUTO SERVICE CENTRE": ("Automotive Services","Battery replacement & roadside","High"),
 "A A A SERVICES CENTER LLC": ("Automotive Services","Vehicle service centre","Medium"),
 "AL AMANA MOTORS ZONE FOR TYRE FIXING & WHEEL ALIGNMENT SERVICES CO L L C": ("Automotive Services","Tyres & wheel alignment","High"),
 "AL NOUF AUTO TYRES & ACCESSORIES": ("Automotive Parts Trading","Tyres & accessories","High"),
 "NASEEM AL RAFAIDIAN TYRES & BATTERIES TRADING": ("Automotive Parts Trading","Tyres & batteries","High"),
 "SAEED ALZAABI TYRE FACTORY LLC": ("Manufacturing - Automotive","Tyre retreading / production","High"),
 "GALADARI MOTOR DRIVING CENTER LLC ": ("Education","Driving school","High"),
 "PARK MY CAR VALET PARKING SERVICES": ("Automotive Services","Valet parking services","High"),
 "ROYAL MELODY CAR PARK RENTAL AND MANAGEMENT LLC": ("Automotive Services","Parking management","High"),
 "AL SALAAM LIMOUSINE L L C": ("Passenger Transport","Limousine & chauffeur services","High"),
 "PRIVATE LIMOUSINE LLC": ("Passenger Transport","Limousine services","High"),
 "WHITE LINE LIMOUSINE LLC": ("Passenger Transport","Limousine services","High"),
 "GRAND CITY LIMOUSINE SERVICES": ("Passenger Transport","Limousine services","High"),
 "WELLCARE PASSENGER TRANSPORT BY LUXURY CAR LLC": ("Passenger Transport","Chauffeur services","High"),
 "AL TAMEEM CARS & BUSES RENTAL LLC": ("Passenger Transport","Vehicle & bus rental","High"),
 "IRVINE CHARTER L L C": ("Passenger Transport","Charter transport services","Medium"),
 "AL TILAL TRANSPORT LLC": ("Freight Transport","Road transport","High"),
 "OASIS STAR TRANSPORT BY HEAVY TRUCKS L L C": ("Freight Transport","Heavy truck transport","High"),
 "ROYAL ATLAS GENERAL TRANSPORT SOLE PROPRIETORSHIP LLC": ("Freight Transport","Road transport","High"),
 "MERIDIAN EXPRESS LOGISTICS LLC": ("Logistics & Supply Chain","Freight & logistics","High"),
 "MASTERGLOBAL LOGISTICS LLC": ("Logistics & Supply Chain","Freight forwarding","High"),
 "VISIUN TRADING AND LOGISTICS FZE": ("Logistics & Supply Chain","Trading & logistics","Medium"),
 "JATCO FREIGHT SERVICES LLC": ("Logistics & Supply Chain","Freight forwarding","High"),
 "KAYBARZ FREIGHT SERVICES L L C": ("Logistics & Supply Chain","Freight forwarding","High"),
 "UNIQUE COURIER CARGO SERVICE LLC": ("Logistics & Supply Chain","Courier & cargo","High"),
 "NINE YARDS SHIPPING & LOGISTICS SERVICES LLC": ("Logistics & Supply Chain","Shipping & logistics","High"),
 "SINOTRANS MIDDLE EAST FZE BRANCH": ("Logistics & Supply Chain","Freight forwarding (Sinotrans)","High"),
 "JVK SHIPPING SERVICES LLC": ("Logistics & Supply Chain","Relocation & shipping","High"),
 "TRANSCAP SHIPPING LINE LLC": ("Shipping","Shipping line / agency","High"),
 "NORTH AFRICA SHIPPING CO": ("Shipping","Shipping & vessel operations","High"),
 "JAWAR AL KHALEEJ SHIPPING LLC": ("Shipping","Shipping services","High"),
 "AHMAD OBAID SHIPPING LLC": ("Shipping","Shipping services","High"),
 "ARIANA WORLD WIDE SHIPPING LLC": ("Shipping","Shipping services","High"),
 "INTER OCEAN SHIP REPAIRS LLC": ("Marine Services","Ship repair","High"),
 "INTER OCEAN SHIP ENGINEERING SERVICES FZE": ("Marine Services","Marine engineering","High"),
 "INTERNATIONAL SHIP REPAIRS FZE": ("Marine Services","Ship repair","High"),
 "AL SUHAIL SHIP MAINTENANCE SERVICES": ("Marine Services","Ship maintenance","High"),
 "SEA FAST MARINE SERVICES LLC": ("Marine Services","Marine services","High"),
 "EXPERT UNITED MARINE SERVICES LLC": ("Marine Services","Marine services","High"),
 "PLUS MARINE & ENGINEERING SERVICES FZE": ("Marine Services","Marine engineering services","High"),
 "TECHNO MARINE EQUIPMENT SERVICES LLC": ("Marine Services","Marine equipment services","High"),
 "DIVERS GROUP LLC": ("Marine Services","Commercial diving & underwater works","High"),
 "K J I MARINA BOATS MANUFACTURING L L C": ("Manufacturing - Marine","Boat building","High"),
 "FUTURE BOATS INDUSTRY L L C": ("Manufacturing - Marine","Boat building","High"),
 "AL FIKREE LEISURE LLC": ("Entertainment & Leisure","Leisure & marine activities","Medium"),
 "TR88HOUSE RESTAURANT AND ENTERTAINMENT CENTER LLC": ("Food Service","Restaurant & entertainment venue","High"),
 "BLACK STAR LOUNGE RESTAURANTS MANAGEMENT LLC": ("Food Service","Restaurant management","High"),
 "NEW GREEN CITY STAR RESTAURANT LLC": ("Food Service","Restaurant","High"),
 "PURANMAL RESTAURANT": ("Food Service","Restaurant","High"),
 "SIRALI RESTAURANT LLC": ("Food Service","Restaurant","High"),
 "PREPMEAL RESTAURANT L L C": ("Food Service","Meal prep & delivery","High"),
 "ABU SAYYAH EXPRESS CAFE & RESTAURANT L L C": ("Food Service","Cafe & restaurant","High"),
 "FUSION CAFE LLC": ("Food Service","Cafe","High"),
 "ESTEKANA CAFE LLC": ("Food Service","Cafe","High"),
 "MIDHAT PASHA CAFE L L C": ("Food Service","Cafe","High"),
 "RETRO 7 CAFE": ("Food Service","Cafe","High"),
 "D O DOTS CAFE": ("Food Service","Cafe","High"),
 "GOURMET HOUSE": ("Food Service","Gourmet food / catering","Medium"),
 "OPORTO MIDDLE EAST": ("Food Service","QSR franchise","High"),
 "MSHAKEK FOODSTUFF CATERING": ("Food Service","Catering","High"),
 "TERRASOL HOSPITALITY SERVICES": ("Hospitality","Hospitality services","Medium"),
 "MUDIN AL EMARATE HOSPITALITY": ("Hospitality","Hospitality services","Medium"),
 "ABDULWAHED BIN SHABIB HOSPITALITIES BR OF ABDULWAHED BIN SHABIB INVESTMENT GROUP L L C": ("Hospitality","Hospitality division of diversified group","High"),
 "FAB MASTER LAUNDRY LLC": ("Laundry Services","Commercial laundry","High"),
 "CAVALIER CLEAN CLEANING BUILDINGS SOLE PROPRIETORSHIP L L C": ("Facilities Management","Building cleaning services","High"),
 "ROMA PROPERTY MANAGEMENT & GENERAL MAINTENANCE SOLE PROPRIETORSHIP L L C": ("Facilities Management","Property management & maintenance","High"),
 "HAIMA EMIRATES BUILDING MAINTENANCE LLC": ("Facilities Management","Building maintenance","High"),
 "DEIRA TOWER ESTATES L L C": ("Real Estate","Property ownership & leasing","High"),
 "ASTON REAL ESTATE LLC": ("Real Estate","Real estate brokerage","High"),
 "CITADEL PROPERTIES LLC": ("Real Estate","Property development / management","High"),
 "MEDAIT STAR REAL ESTATE LLC": ("Real Estate","Real estate services","High"),
 "HMK REAL ESTATE DEVELOPMENT LLC": ("Real Estate","Property development","High"),
 "REVI REAL ESTATE DEVELOPMENT": ("Real Estate","Property development","High"),
 "MALAIH INVESTMENT & PROJECTS DEVELOPMENT L L C": ("Real Estate","Investment & project development","Medium"),
 "ALWATHBA INVESTMENT LLC": ("Investment & Holding","Investment company","Medium"),
 "SAT INVESTMENTS LLC": ("Investment & Holding","Investment company","Medium"),
 "COASTAL INVESTMENT": ("Investment & Holding","Investment company","Medium"),
 "DEMIND INVESTMENT": ("Investment & Holding","Investment company","Medium"),
 "BAY GATE INVESTMENT L L C": ("Investment & Holding","Investment company","Medium"),
 "SEVEN EMIRATES INVESTMENT LLC": ("Investment & Holding","Investment company","Medium"),
 "ABDULLA AL ARIF INVESTMENT": ("Investment & Holding","Investment company","Medium"),
 "A G C INVESTMENT L L C": ("Investment & Holding","Investment company","Medium"),
 "RETAIL & BEYOND COMMERCIAL INVESTMENT L L C": ("Retail","Retail investment & operations","Medium"),
 "EMIRATES ROYAL HOLDING LLC": ("Investment & Holding","Holding company","Medium"),
 "APEX HOLDING LLC": ("Investment & Holding","Holding company","Medium"),
 "MQ HOLDING GROUP LLC": ("Investment & Holding","Holding company","Medium"),
 "AW BIN SHABIB INVESTMENT LLC": ("Diversified Group","Investment group - FMCG, industry & services","High"),
 "ABDULWAHED BIN SHABIB INVESTMENT GROUP L L C": ("Diversified Group","Investment group - FMCG, industry & services","High"),
 "ABDULWAHED BIN SHABIB INVESTMENT GROUP LLC": ("Diversified Group","Investment group - FMCG, industry & services","High"),
 "NATIONAL HOLDING AND AL MOJIL LLC": ("Diversified Group","Holding & contracting group","Medium"),
 "AL HOSON GROUPS": ("Diversified Group","Diversified group","Medium"),
 "AL JABALI GROUP": ("Diversified Group","Diversified group","Medium"),
 "MAB GROUP": ("Diversified Group","Diversified group","Medium"),
 "RVS GROUP": ("Diversified Group","Diversified group","Low"),
 "RIDGE GROUP": ("Diversified Group","Diversified group","Low"),
 "MORYA GROUP": ("Diversified Group","Diversified group","Low"),
 "NICE GROUP OF COMPANIES": ("Diversified Group","Diversified group","Low"),
 "MOHEBZADA GROUP OF COMPANIES": ("Diversified Group","Diversified group","Medium"),
 "AL SWAYEH GROUP OF COMPANIES": ("Diversified Group","Diversified group","Medium"),
 "SAFE LINE GROUP OF COMPANIES LLC": ("Diversified Group","Electromechanical & trading group","Medium"),
 "LUCENT GROUP OF COMPANIES": ("Diversified Group","Diversified group","Low"),
 "EXCELLENCY GROUP OF MANAGEMENT COMPANIES": ("Professional Services","Business management services","Medium"),
 "F A H GROUP": ("Diversified Group","Diversified group","Low"),
 "MOHD RIYAZ GROUP": ("Diversified Group","Diversified group","Low"),
 "FAKHREE AL HINDI GROUP": ("Diversified Group","Diversified group","Low"),
 "SAADCO GROUP": ("Diversified Group","Diversified group","Low"),
 "AL AJDAN GROUP": ("Diversified Group","Diversified group","Low"),
 "CROWN PACIFIC GROUP FZE": ("Trading & Distribution","International trading group","Medium"),
 "AMIT INTERNATIONAL GROUP FZE": ("Trading & Distribution","International trading","Medium"),
 "AMIT RETAIL LLC": ("Retail","Retail operations","Medium"),
 "RGM INTERNATIONAL GROUP LLC": ("Trading & Distribution","International trading","Low"),
 "TANWEER GROUP SA": ("Trading & Distribution","International trading","Low"),
 "MIDDLE EAST GROUP FZE": ("Trading & Distribution","International trading","Low"),
 "PARCO GROUP ABU DHABI REGION": ("Food & Beverage Trading","FMCG distribution","Medium"),
 "PARCO MIDDLE EAST LLC": ("Food & Beverage Trading","FMCG distribution","Medium"),
 "AWS DISTRIBUTION": ("Distribution","FMCG / consumer goods distribution","Medium"),
 "AWS EUROPE LTD": ("Distribution","Consumer goods distribution","Medium"),
 "AWS AVENUE COMPANY FOR TRADING": ("Trading & Distribution","General trading","Low"),
 "DISTRIBUCORP GULF FZE": ("Distribution","Consumer goods distribution","Medium"),
 "OVERSEAS DISTRIBUTION SERVICES INC": ("Distribution","Distribution services","Medium"),
 "KTC INTERNATIONAL LLC": ("Trading & Distribution","International trading","Low"),
 "NITIN VENTURES FZE": ("Trading & Distribution","Commodity / general trading","Low"),
 "GOBIND INTERNATIONAL FZCO": ("Trading & Distribution","General trading","Low"),
 "MANEESH INTERNATIONAL FZCO": ("Trading & Distribution","General trading","Low"),
 "OVIYAM INTERNATIONAL PTE LTD": ("Trading & Distribution","General trading","Low"),
 "ARPAN INTERNATIONAL FZC": ("Trading & Distribution","General trading","Low"),
 "EXTOL INTERNATIONAL FZC": ("Trading & Distribution","General trading","Low"),
 "MULTI COMMERCE FZC": ("Trading & Distribution","General trading","Low"),
 "MULTI TRADE LIMITED FZC": ("Trading & Distribution","General trading","Low"),
 "MULTI COMMODITY GENERAL TRADING FZE": ("Commodity Trading","Commodity trading","Medium"),
 "MULTI GRAIN TRADING LLC": ("Commodity Trading","Grain trading","High"),
 "MULTI PRODUCTS ENTERPRISE L L C": ("Trading & Distribution","General trading","Low"),
 "CASPIAN GULF FZE": ("Trading & Distribution","General trading","Low"),
 "NORTH CASPIAN TRADING L L C": ("Trading & Distribution","General trading","Low"),
 "AFRIEXPO FZE": ("Trading & Distribution","Africa-focused export trading","Medium"),
 "GEEPEE INDUSTRIES LTD": ("Manufacturing - Plastics","Plastic products manufacturing","Medium"),
 "KARAM INDUSTRIA LIMITIDA": ("Manufacturing","Industrial manufacturing (Africa)","Low"),
 "KARAM INDUSTRIES NAMIBIA PTY LTD": ("Manufacturing","Industrial manufacturing (Africa)","Low"),
 "JAYSONS MULTI TRADE AND INDUSTRIES SUARL": ("Trading & Distribution","Trading & light manufacturing","Low"),
 "GUANGZHOU AFRA INDUSTRIES CO LTD": ("Manufacturing","Manufacturing & export (China)","Low"),
 "J J EXPORTERS JUSTINE PAIGE BVI LTD": ("Trading & Distribution","Export trading","Low"),
 "ESSAMEL SAID EXPORT & IMPORT": ("Trading & Distribution","Import / export","Medium"),
 "NIYOJAN CONNECTOR OVERSEAS LLP": ("Trading & Distribution","Export trading","Low"),
 "VEEMA UK LIMITED T/AS RUPALI": ("Food & Beverage Trading","Food brand / distribution","Low"),
 "MAHALAKSHMI INDUSTRIAL GEARS PRIVATE LIMITED": ("Manufacturing - Machinery","Industrial gears","High"),
 "SPACEAGE ELECTRICAL SWITCHGEAR CO WLL": ("Manufacturing - Electrical","LV switchgear panels","High"),
 "EVERSHINE ELECT SWITCHGEAR MFG L L C": ("Manufacturing - Electrical","LV switchgear panels","High"),
 "LINK LIGHT SWITCHGEAR INDUSTRIES LLC": ("Manufacturing - Electrical","LV switchgear panels","High"),
 "SWITCHGEAR ELECTRO MECHANICAL LLC": ("MEP & Electromechanical","Switchgear & electromechanical works","High"),
 "NATIONAL ELECTRICAL SYSTEM FZE": ("Electrical Trading","Electrical products & systems","High"),
 "3S LIGHTING SOLUTIONS LLC": ("Electrical Trading","Lighting solutions","High"),
 "FLUX LIGHT GENERAL TRADING LLC": ("Electrical Trading","Lighting products","High"),
 "TODAY LIGHT TRADING L L C": ("Electrical Trading","Lighting products","High"),
 "ELECTROFOS DESIGNS LLC": ("Electrical Trading","Lighting design & supply","High"),
 "ENLITE TECHNOLOGIES DMCC": ("Electrical Trading","Lighting technology","High"),
 "WINGS POWER SOLUTIONS": ("Power Generation Equipment","Power / generator solutions","Medium"),
 "ELECTROMECH FZE": ("MEP & Electromechanical","Electromechanical services","Medium"),
 "AL BASRA ELECTROMECHANICAL LLC": ("MEP & Electromechanical","MEP contracting","High"),
 "AL BASRA ELECTRICAL & SANITARY CONT L L C": ("MEP & Electromechanical","Electrical & plumbing contracting","High"),
 "CONTROL & APPLICATIONS EMIRATES L L C": ("MEP & Electromechanical","Control systems & instrumentation","High"),
 "S W M E CONTROL SYSTEMS TRADING LLC": ("Industrial Automation","Control systems supply","High"),
 "ROVE AUTOMATION & INSTAL WORKS L L C": ("Industrial Automation","Automation & installation","High"),
 "ADVANCED INTEGRATION TECHNOLOGIES SP LLC": ("Industrial Automation","Systems integration","High"),
 "AMPS MIDDLE EAST FZ LLC": ("Industrial Automation","Automation & power systems","Medium"),
 "GEOBIT INTERNATIONAL FZC": ("Industrial Distribution","Survey / geotechnical equipment","Medium"),
 "GODOBA PORTAL LLC": ("E-commerce","Online marketplace / portal","Medium"),
 "AANACART": ("E-commerce","Online retail platform","Medium"),
 "RFM LOYALTY CO LLC": ("Marketing Services","Loyalty & CRM programmes","High"),
 "A ONE ADVERTISING LLC": ("Marketing Services","Advertising & signage","High"),
 "ART PALACE ADVERTISING AND PRODUCTION": ("Marketing Services","Advertising & production","High"),
 "SHINEJOIN WEB DESIGN LLC": ("Marketing Services","Web design & digital","High"),
 "VMP CONSULTANCY": ("Professional Services","Business consultancy","Medium"),
 "UNIVERSAL BLUE OCEAN CONSULTANT": ("Professional Services","Business consultancy","Medium"),
 "MEVAGO BUSINESS RESOURCES EST": ("Professional Services","Business services","Low"),
 "APJ MANAGEMENT": ("Professional Services","Business management services","Low"),
 "KATARA PROJECT MANAGEMENT SERVICE LLC": ("Project & Cost Consultancy","Project management","High"),
 "ESTIDAMA ENGINEERING CONSULTING SOLE PROPRIETORSHIP L L C": ("Engineering Consultancy","Engineering consultancy","High"),
 "MEETHAQ EMPLOYMENT AGENCY": ("HR & Recruitment","Employment agency","High"),
 "MEETHAQ MANPOWER LLC": ("HR & Recruitment","Manpower supply","High"),
 "JUMBO MANPOWER SERVICES LLC": ("HR & Recruitment","Manpower supply","High"),
 "STALLION ON DEMAND LABOR SUPPLY LLC": ("HR & Recruitment","Labour supply","High"),
 "SKY HIGH HR PROVISION SERVICES LLC SPC": ("HR & Recruitment","HR services","High"),
 "STREAM RECRUITMENT SOLE PROPRIERSHIP LLC": ("HR & Recruitment","Recruitment services","High"),
 "YAZWAA RECRUITMENT L L C": ("HR & Recruitment","Recruitment services","High"),
 "YAZWAA RECRUITMENT SOLE PROPRIETORSHIP LLC": ("HR & Recruitment","Recruitment services","High"),
 "AL RAWABIT INTERNATIONAL RECRUITMENT L L C": ("HR & Recruitment","Recruitment services","High"),
 "MAIMOON PAPERS INDUSTRY LLC": ("Manufacturing - Paper & Packaging","Paper products","High"),
 "SOFT & HYGIENIC PAPER MANUFACTURING LLC": ("Manufacturing - Paper & Packaging","Tissue & hygiene paper","High"),
 "QUALITY WIPES LLC": ("Manufacturing - Paper & Packaging","Wet wipes production","High"),
 "ZIVA WET WIPES FZCO": ("Manufacturing - Paper & Packaging","Wet wipes production","High"),
 "ECO KRAFT INDUSTRIES L L C": ("Manufacturing - Paper & Packaging","Kraft paper & packaging","High"),
 "STAR PACK PACKAGING INDUSTRY L L C": ("Manufacturing - Paper & Packaging","Packaging production","High"),
 "VUEGA PACKING INDUSTRIES": ("Manufacturing - Paper & Packaging","Packaging production","High"),
 "EXPRESS FLEXI PACK": ("Manufacturing - Paper & Packaging","Flexible packaging","High"),
 "MODPAK LLC": ("Manufacturing - Paper & Packaging","Packaging","High"),
 "PALLETCO LLC": ("Manufacturing - Paper & Packaging","Pallets manufacturing","High"),
 "OVERSEAS CANS & CONTAINERS LLC": ("Manufacturing - Paper & Packaging","Metal cans & containers","High"),
 "SNH PACKING GENERAL TRADING LLC": ("Packaging Trading","Packaging materials trading","High"),
 "PRESS PACK TRADING L L C": ("Packaging Trading","Packaging materials trading","High"),
 "DURA PRINTING MATERIALS TRADING L L C": ("Printing & Publishing","Printing materials supply","High"),
 "SEVEN EMIRATES PLASTIC CONTAINER TRADING LLC": ("Packaging Trading","Plastic containers trading","High"),
 "AL BORJ PLASTIC INDUSTRIES COMPANY LLC": ("Manufacturing - Plastics","Plastic products","High"),
 "GHANTOOT PLASTIC INDUSTRIES": ("Manufacturing - Plastics","Plastic products","High"),
 "FUJAIRAH PLASTIC FACTORY": ("Manufacturing - Plastics","Plastic products","High"),
 "INNOTECH POLYMERS MANUFACTURER LLC": ("Manufacturing - Plastics","Polymer products","High"),
 "AL SHARQ PLAS LLC": ("Manufacturing - Plastics","Plastic products","High"),
 "MEGASTRIKE MIDDLE EAST POLYMERS TRADING LLC": ("Chemicals Distribution","Polymers trading","High"),
 "MEGASTRIKE MIDDLE EAST & AFRICA FZCO": ("Chemicals Distribution","Polymers & chemicals trading","Medium"),
 "AHMED AL MAGHREBI PERFUME MANUF LLC": ("Manufacturing - Cosmetics","Perfume manufacturing","High"),
 "DXB PERFUMES FACTORY LLC": ("Manufacturing - Cosmetics","Perfume manufacturing","High"),
 "LOPAZ PERFUMES INDUSTRY LLC": ("Manufacturing - Cosmetics","Perfume manufacturing","High"),
 "AL JOTHAN PERFUMES": ("Cosmetics & Personal Care","Perfume trading & retail","High"),
 "KHALIS PERFUMES TRADING LLC": ("Cosmetics & Personal Care","Perfume trading","High"),
 "ORIENTAL ESSENCE GENERAL TRADING LLC": ("Cosmetics & Personal Care","Fragrance / oud trading","Medium"),
 "BEAUTY CHINA TRADING LLC": ("Cosmetics & Personal Care","Beauty products trading","High"),
 "BEAUTY OASIS GENERAL TRADING LLC": ("Cosmetics & Personal Care","Beauty products trading","High"),
 "ZAYAN COSMETICS TRADING": ("Cosmetics & Personal Care","Cosmetics trading","High"),
 "DERMA HEALTH COSMETICS TR": ("Cosmetics & Personal Care","Dermo-cosmetics trading","High"),
 "BIOSCIENCE GMBH COSMETICS TRADING LLC": ("Cosmetics & Personal Care","Cosmetics trading","High"),
 "AESTHETIX TECHNOLOGIES LLC": ("Medical & Diagnostics","Aesthetic medical devices","High"),
 "BIO FOOT HEALTH CARE MEDICAL EQUIPMENTS LLC": ("Medical Supplies","Orthopaedic / podiatry products","High"),
 "NEW AL FARWANIYA SURGICALS & MEDICAL EQUIPMENT L L C": ("Medical Supplies","Surgical & medical equipment","High"),
 "OTEX MEDICAL EQUIPMENTS TRADING LLC": ("Medical Supplies","Medical equipment trading","High"),
 "AL MOSTAQBAL MEDICAL STORE L L C": ("Medical Supplies","Medical supplies","High"),
 "ABCON INTERNATIONAL DRUG STORE LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "LUNATUS DRUG STORE": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "ROYAL PHARMACEUTICAL DRUG STORE LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "MOHAMED ALI MOIDEEN DRUG STORE FZE": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "BIN SHABIB DRUG STORE BR OF AW BIN SHABIB INVESTMENT LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "AL KENZ PHARMACEUTICAL PRODUCTS LLC": ("Pharmaceuticals","Pharmaceutical products","High"),
 "CEDAR PHARMACEUTICALS LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "AL HAYAT PHARMACEUTICALS": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "AL HAYAT PHARMACEUTICALS LLC SP": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "ACORUS PHARMA LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "DUPHARM LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "SMART PHARMA TRADING LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "MUSCAT PHARMACEUTICAL TRADING LLC": ("Pharmaceuticals","Pharmaceutical distribution","High"),
 "OZONE PHARMACY L L C": ("Pharmacy Retail","Community pharmacy","High"),
 "ASTON PHARMACY LLC": ("Pharmacy Retail","Community pharmacy","High"),
 "ALAHLIYA ALAIN PHARMACY": ("Pharmacy Retail","Community pharmacy","High"),
 "NEOM PHARMACY L L C O P C": ("Pharmacy Retail","Community pharmacy","High"),
 "RANA MEDICAL CENTER PHARMACY": ("Pharmacy Retail","Clinic pharmacy","High"),
 "AL MAGD CENTER PHARMACY L L C SOLE PROPRIETORSHIP L L C": ("Pharmacy Retail","Community pharmacy","High"),
 "METRO INTERNATIONAL MEDICAL CENTER PHARMACY L L C": ("Pharmacy Retail","Clinic pharmacy","High"),
 "PHARMACY EXCELLENCY GHAYATHI POLY CLINICS L L C": ("Healthcare","Polyclinic & pharmacy","High"),
 "ALAM SUPER MARKET LLC": ("Retail","Supermarket","High"),
 "HASHIM HYPERMARKET LLC": ("Retail","Hypermarket","High"),
 "EDO DEPARTMENT STORE L L C": ("Retail","Department store","High"),
 "AAGT INTERNATIONAL SURPLUS STORE": ("Retail","Surplus / discount retail","Medium"),
 "NATIONAL STORE LLC": ("Retail","Retail & distribution","Medium"),
 "SAVER GROCERY FOOD STUFF TRADING LLC": ("Retail","Grocery retail","High"),
 "KHAMAS COLD STORES": ("Food & Beverage Trading","Cold storage & foodstuff distribution","High"),
 "GREEN BELT STAR INTERNATIONAL COLD STORE": ("Food & Beverage Trading","Cold store & foodstuff distribution","High"),
 "KHAMAS GENERAL TRADING AND STORES": ("Trading & Distribution","General trading","Medium"),
 "MOHIDEEN TRADERS FISH MARKET": ("Fresh Produce & Grocery","Fish wholesale","High"),
 "MOHIDEEN VEGETABLE AL HABAY FOOD STUFF DIVISION": ("Fresh Produce & Grocery","Vegetables & foodstuff","High"),
 "AL HABAY TRADING CO": ("Food & Beverage Trading","Foodstuff trading","Medium"),
 "ABU HAIL FOODSTUFF TRADING": ("Food & Beverage Trading","Foodstuff trading","High"),
 "AL ASEEL EGGS TRADING": ("Fresh Produce & Grocery","Eggs wholesale","High"),
 "WADI AL TAIEF EGGS TRADING LLC": ("Fresh Produce & Grocery","Eggs wholesale","High"),
 "AL KARAMA MEAT TRADING LLC": ("Fresh Produce & Grocery","Meat wholesale","High"),
 "AL AMIN FRESH FRUITS": ("Fresh Produce & Grocery","Fruits wholesale","High"),
 "DELICIOUS FRUITS LTD": ("Fresh Produce & Grocery","Fruits trading","High"),
 "CASH CUSTOMER": ("Not a company","Walk-in / cash sales ledger account","High"),
 "QASSIM": ("Unclassified","Insufficient information in name","Low"),
 "PANAGIA": ("Unclassified","Insufficient information in name","Low"),
 "BINDALMOUK": ("Unclassified","Insufficient information in name","Low"),
 "ANAH LLC": ("Unclassified","Insufficient information in name","Low"),
 "HATCO": ("Unclassified","Insufficient information in name","Low"),
 "ICEM": ("Unclassified","Insufficient information in name","Low"),
 "CIMAC": ("Unclassified","Insufficient information in name","Low"),
 "TERZETTO": ("Unclassified","Insufficient information in name","Low"),
 "TJJ & CO": ("Unclassified","Insufficient information in name","Low"),
 "ROY PAUL": ("Individual / Personal Account","Named individual, not a company","Medium"),
 "RAMESH HIRA": ("Individual / Personal Account","Named individual, not a company","Medium"),
 "MOHAMMAD JAWAD YOUSUF KHOORY": ("Individual / Personal Account","Named individual / sole trader","Medium"),
 "2/8 KRASNODAR": ("Unclassified","Insufficient information in name","Low"),
 "4 CORNERS": ("Unclassified","Insufficient information in name","Low"),
 "COMPANY T R E": ("Unclassified","Insufficient information in name","Low"),
 "QASIR AL KHAN USED ELECTRONICS DEVICES TRADING LLC": ("Consumer Electronics","Used electronics trading","High"),
 "KUKOO ELECTRONICS TRADING LLC": ("Consumer Electronics","Electronics trading","High"),
 "TABBARA ELECTRONICS LLC": ("Consumer Electronics","Electronics distribution","High"),
 "FOX ELECTRONICS FZ LLC": ("Consumer Electronics","Electronics distribution","High"),
 "QUALIA ELECTRONICS TRADING LLC": ("Consumer Electronics","Electronics trading","High"),
 "MASTER GADGET FZCO": ("Consumer Electronics","Consumer gadgets trading","High"),
 "SOUNDME WORLD FZE": ("Consumer Electronics","Audio products trading","High"),
 "AVGO MIDDLE EAST FZE": ("Consumer Electronics","Electronics / appliances distribution","Medium"),
 "RECHARGE QATAR W L L": ("Telecommunications","Prepaid / recharge services","Medium"),
 "RAYWOOD COMMUNICATIONS L L C": ("Telecommunications","Communications services","Medium"),
 "LEISUNG TECHNOLOGIES LLC": ("Technology","Technology products & solutions","Low"),
 "HEXATECH INTERNATIONAL HQ": ("Technology","Technology solutions","Low"),
 "CALCULAZ INTERNATIONAL FZE": ("Technology","Technology / business solutions","Low"),
 "CYNGBEL LLC": ("Unclassified","Insufficient information in name","Low"),
 "HUEGO LTD": ("Unclassified","Insufficient information in name","Low"),
 "CASAL LLC": ("Unclassified","Insufficient information in name","Low"),
 "BASE LLC": ("Unclassified","Insufficient information in name","Low"),
 "BLUE LINE ESTABLISHMENT": ("Unclassified","Insufficient information in name","Low"),
 "BLUE LINE L L C S P C": ("Unclassified","Insufficient information in name","Low"),
 "VISION PLUS": ("Unclassified","Insufficient information in name","Low"),
 "NEW WORLD CENTER": ("Unclassified","Insufficient information in name","Low"),
 "NEW WORLD CO LLC": ("Unclassified","Insufficient information in name","Low"),
 "GHM INTERNATIONAL": ("Unclassified","Insufficient information in name","Low"),
 "PANAGIA ": ("Unclassified","Insufficient information in name","Low"),
 "RBI HAWKER": ("Unclassified","Insufficient information in name","Low"),
 "RBIH MIDDLE EAST FZE": ("Unclassified","Insufficient information in name","Low"),
 "OBS GROUP LLC": ("Diversified Group","Diversified group","Low"),
 "MFIVE SERVICES": ("Unclassified","Insufficient information in name","Low"),
 "BMJ INDUSTRIES FZ LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "KADRIS INDUSTRIES FZE": ("Manufacturing","Industrial manufacturing","Low"),
 "AVANT INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "BERG INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "ROCKANY INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "QUANTUM INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "BEST CHOICE INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "AHMAD INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "AL AREEN INDUSTRIES": ("Manufacturing","Industrial manufacturing","Low"),
 "FEATHER TOUCH INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "EXCEL INDUSTRY CO LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "AL GHAITH INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Medium"),
 "AL HAMAD INDUSTRIES INTERNATIONAL F Z C": ("Manufacturing","Industrial manufacturing","Low"),
 "FASTEC INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "FOURTECH INDUSTRIES LLC": ("Manufacturing","Industrial manufacturing","Low"),
 "MIDDLE EAST FACTORY L L C": ("Manufacturing","Industrial manufacturing","Low"),
 "AL WAHA MECHANICAL INDUSTRIES LLC": ("Manufacturing - Machinery","Mechanical products","Medium"),
 "ABDULWAHED BIN SHABIB INDUSTRY FZ LLC": ("Manufacturing","Industrial division of diversified group","Medium"),
 "ABDULWAHED BIN SHABIB FOOD INDUSTRIES L L C": ("Manufacturing - Food","Food production","High"),
 "ABDULWAHED BIN SHABIB FOOD INDUSTRIES BR OF AW BIN SHABIB INVESTMENT L L C": ("Manufacturing - Food","Food production","High"),
 "ABDULWAHED BIN SHABIB SECURITY SYSTEM BR OF AW BIN SHABIB INVESTMENT L L C": ("Security Systems","Security systems division","High"),
 "SPEEDY TECHNICAL SERVICES BR OF ABDULWAHED BIN SHABIB INVESTMENT GROUP LLC": ("Technical Services","Technical / maintenance services","High"),
 "AL MASOOD BERGUM": ("Industrial Equipment","Industrial products & equipment","Low"),
 "NASER MOHD NASER AL SAYER TRADING CO L L C": ("Trading & Distribution","General trading","Low"),
 "GREEN COOLING L L C SP": ("HVAC Services","Cooling & HVAC services","High"),
 "BRIGHT LINE REFRIGERATION AND AIR CONDITIONING TRADING LLC": ("HVAC Trading","Refrigeration & AC equipment","High"),
 "CASTLE REFRIGERATION EQUIPMENT TRADING LLC": ("HVAC Trading","Refrigeration equipment","High"),
 "WEATHER GULF AIR CONDITION TRADING LLC": ("HVAC Trading","Air conditioning equipment","High"),
 "FALCON PROFESSIONAL KITCHEN LLC": ("Commercial Kitchen Equipment","Professional kitchen equipment","High"),
 "QUALITY KITCHEN EQUIPMENT TRADING LLC": ("Commercial Kitchen Equipment","Kitchen equipment trading","High"),
 "RADIANT FILTERS TRADING CO LLC": ("Industrial Distribution","Filters & filtration products","High"),
 "RIGHT CHOICE EQUIPMENT TRADING LLC": ("Industrial Equipment","Equipment trading","Medium"),
 "MUSCUT TECHNICAL EQUIPMENT LLC": ("Industrial Equipment","Technical equipment supply","Medium"),
 "DELTRON MECHANICAL EQUIPMENT TRADING": ("Industrial Equipment","Mechanical equipment trading","High"),
 "ALLIANCE MECHANICAL EQUIPMENT": ("Industrial Equipment","Mechanical equipment supply","High"),
 "AL MESHARI HEAVY EQUIPMENT TRADING": ("Heavy Equipment","Heavy equipment trading","High"),
 "NUMBER ONE HEAVY EQUIPMENT L L C": ("Heavy Equipment","Heavy equipment","High"),
 "DESERT EAGLE HEAVY EQUIPMENT RENTAL LLC": ("Equipment Rental","Heavy equipment rental","High"),
 "DESERT KING HEAVY EQPT RENTAL L L C": ("Equipment Rental","Heavy equipment rental","High"),
 "DESERT KING QATAR HEAVY EQUIPMENT RENTAL & CONTRACTING W L L": ("Equipment Rental","Heavy equipment rental & contracting","High"),
 "SMART ZONE HEAVY EQUIPMENT RENTAL LLC": ("Equipment Rental","Heavy equipment rental","High"),
 "SMARTLIFT HANDLING LOADING & LIFTING EQUIPMENT RENTAL L L C": ("Equipment Rental","Lifting equipment rental","High"),
 "BUSS ENGINEERING & HEAVY EQUIPMENT REPAIRING LLC": ("Equipment Maintenance","Heavy equipment repair","High"),
 "EQUIPTEC EQUIPMENTS REPAIRING L L C": ("Equipment Maintenance","Equipment repair","High"),
 "SEVEN DAYS EQUIPMENT MAINTENANCE LLC": ("Equipment Maintenance","Equipment maintenance","High"),
 "AUTOMECH ENGINEERING CO LLC": ("Equipment Maintenance","Automotive & mechanical engineering","High"),
 "BENNETT ENGINEERING LLC": ("Engineering Services","Engineering services","Medium"),
 "KNM ENGINEERING": ("Engineering Services","Engineering services","Medium"),
 "HYDROFIT ENGINEERING": ("Engineering Services","Hydraulics engineering","Medium"),
 "HYDROFIT TRADING": ("Industrial Distribution","Hydraulic products trading","High"),
 "HYDROFIT TRADING LLC": ("Industrial Distribution","Hydraulic products trading","High"),
 "HYDROFIT TRADING LLC BR 1": ("Industrial Distribution","Hydraulic products trading","High"),
 "NEW SYSTEM ENGINEERING LLC": ("Engineering Services","Engineering services","Medium"),
 "SILVERTECH ENGINEERING LLC": ("Engineering Services","Engineering services","Medium"),
 "FOURTECH ENGINEERING L L C": ("Engineering Services","Engineering services","Medium"),
 "ENGINEERS MIDDLE EAST FZCO": ("Engineering Services","Engineering services","Medium"),
 "AL FATTAN ENGINEERING L L C": ("Engineering Services","Engineering & contracting","Medium"),
 "ALBWARDY ENGINEERING ENTERPRISES EST": ("Engineering Services","Engineering & contracting","High"),
 "ALBWARDY ENGINEERING ENTERPRISES L L C": ("Engineering Services","Engineering & contracting","High"),
 "ALBWARDY ENGINEERING ENTERPRISES LLC": ("Engineering Services","Engineering & contracting","High"),
 "AL BWARDY TECHNICAL & INDUSTRIAL L L C": ("Engineering Services","Technical & industrial services","High"),
 "AL BWARDY TECHNICAL & INDUSTRIAL LLC": ("Engineering Services","Technical & industrial services","High"),
 "HAROON ENG MAT MARKETING CO LLC": ("Industrial Distribution","Engineering materials marketing","High"),
 "CONSTRUCTION DYNAMICS": ("Construction & Contracting","Contracting","High"),
 "AL NASR CONSTRUCTION DYNAMICS": ("Construction & Contracting","Contracting","High"),
 "GEOSAN CONSTRUCTION DYNAMICS": ("Construction & Contracting","Contracting","High"),
 "AUTOCAD CONSTRUCTION": ("Construction & Contracting","Contracting","Medium"),
 "ROBODH-DHEERAJ JOINT VENTURE": ("Construction & Contracting","Contracting joint venture","High"),
 "NASSER SAEED ALHAJRI & PARTNERS CONTRACTING COMPANY L L C": ("Construction & Contracting","Industrial contracting (NSH)","High"),
 "SEIDCO GENERAL CONTRACTING": ("Construction & Contracting","General contracting","High"),
 "GENERAL CONSTRUCTION COMPANY W L L": ("Construction & Contracting","General contracting","High"),
 "ARABIAN COAST CONTRACTING LLC": ("Construction & Contracting","General contracting","High"),
 "AL MANZA TRADING": ("Trading & Distribution","General trading","Low"),
 "SAFA TRADING": ("Trading & Distribution","General trading","Low"),
 "CONCAVE TRADING": ("Trading & Distribution","General trading","Low"),
 "PRONC TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "PRONYX TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "FALCON TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "GALAXY TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "PRISM TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "KANMO TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "MASEERA TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "BAFCO TRADING LLC": ("Furniture & Interiors","Office furniture & interiors","High"),
 "NASCO TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "TOPCOAT TRADING LLC": ("Building Materials Trading","Paints & coatings","High"),
 "SPECTRUM INT'L L L C": ("Trading & Distribution","General trading","Low"),
 "ARCOMA COMMERCIAL AGENCIES LLC": ("Trading & Distribution","Commercial agencies & distribution","Medium"),
 "SHATRY TRADING ESTABLISHMENT": ("Trading & Distribution","General trading","Low"),
 "AL RIQABAT TRADING ESTABLISHMENT": ("Trading & Distribution","General trading","Low"),
 "SALALAH FUTURE TRADING": ("Trading & Distribution","General trading","Low"),
 "SUMMER CRESCENT TRADING COMPANY": ("Trading & Distribution","General trading","Low"),
 "SHAKER ALI AL-SAMAD TRADING CO": ("Trading & Distribution","General trading","Low"),
 "HASSAN AL QURASHI TRADING COMPANY": ("Trading & Distribution","General trading","Low"),
 "AL AREEN TRADING CO LLC": ("Trading & Distribution","General trading","Low"),
 "GHAZALCO TRADING EST": ("Trading & Distribution","General trading","Low"),
 "AL GUTAIL TRADING EST": ("Trading & Distribution","General trading","Low"),
 "AL KILANI TRADING CO": ("Trading & Distribution","General trading","Low"),
 "AL KILANI TRADING EST": ("Trading & Distribution","General trading","Low"),
 "ABUSEEDO TRADING EST": ("Trading & Distribution","General trading","Low"),
 "HUSSEIN BEHESHTI TRADING": ("Trading & Distribution","General trading","Low"),
 "BEERAN KUTTY TRADING": ("Trading & Distribution","General trading","Low"),
 "AHMED REZA TRADING CO": ("Trading & Distribution","General trading","Low"),
 "MOTIVE INTERNATIONAL TRADING": ("Trading & Distribution","General trading","Low"),
 "INTER CITY TRADING LLC": ("Trading & Distribution","General trading","Low"),
 "CONCORDIA INTERNATIONAL MIDDLE EAST FZ LLC ": ("Facilities Management","Integrated FM services","High"),
}

# ---------------------------------------------------------------
# 2. ORDERED KEYWORD RULES (most specific first)
# ---------------------------------------------------------------
RULES = [
 # --- food / produce ---
 (r'\bVEG(E|I)TABLES?\b|\bVEG &|\bFRUITS?\b|\bFRESH PRODUCE\b|\bPOTATOES\b|\bFRESH FRUITS\b',
   "Fresh Produce & Grocery","Fruits & vegetables wholesale"),
 (r'\bFISH\b|\bSEAFOOD\b|\bMEAT\b|\bPOULTRY\b|\bEGGS\b',
   "Fresh Produce & Grocery","Meat / seafood wholesale"),
 (r'\bFOOD ?STUFF\b|\bFOODSUFF\b|\bFOOD STUFF\b',
   "Food & Beverage Trading","Foodstuff wholesale & distribution"),
 (r'\bFOOD INDUSTR|\bFOOD PROCESSING\b|\bFOOD MANUFACTURING\b|\bDAIRY\b|\bBAKERY\b|\bCHOCOLATE\b|\bCONFECTION',
   "Manufacturing - Food","Food production"),
 (r'\bFOODS?\b|\bGRAIN\b|\bRICE\b|\bTEA\b|\bCOFFEE\b|\bJUICE',
   "Food & Beverage Trading","Food & beverage distribution"),
 (r'\bRESTAURANT|\bCAFE\b|\bCATERING\b|\bCAFETERIA\b|\bSWEETS\b|\bPASTRY\b',
   "Food Service","Restaurants & catering"),
 (r'\bSUPER ?MARKET\b|\bHYPERMARKET\b|\bGROCERY\b',
   "Retail","Grocery retail"),
 (r'\bTOBACCO\b|\bCIGARETTE',
   "Manufacturing - Tobacco","Tobacco products"),

 # --- automotive ---
 (r'\bAUTO ?SPARE ?PARTS?\b|\bSPARE ?PARTS?\b|\bAUTO ?PARTS?\b|\bCAR SPARE PARTS\b|\bAUTOSPARES\b|\bSPAREPARTS\b',
   "Automotive Parts Trading","Vehicle spare parts & accessories"),
 (r'\bTYRES?\b|\bTIRES?\b|\bBATTER(Y|IES)\b',
   "Automotive Parts Trading","Tyres & batteries"),
 (r'\bGARAGE\b|\bAUTO REPAIR|\bAUTO SERVICE|\bAUTO CARE\b|\bWHEEL ALIGNMENT\b',
   "Automotive Services","Vehicle repair & servicing"),
 (r'\bMOTORS?\b|\bVEHICLES?\b|\bAUTOMOTIVE\b|\bAUTO ',
   "Automotive","Vehicles, parts & services"),

 # --- oil, gas, energy ---
 (r'\bOIL ?FIELD\b|\bOILFIELD\b|\bPETROLEUM\b|\bPETRO\b|\bDRILLING\b|\bOIL & GAS\b|\bOIL AND GAS\b',
   "Oil & Gas Services","Oilfield services & supply"),
 (r'\bENERGY\b',
   "Energy","Energy services & products"),

 # --- marine / shipping / logistics ---
 (r'\bSHIP ?REPAIR|\bSHIP ?ENGINEERING|\bSHIP MAINTENANCE|\bMARINE\b|\bBOATS?\b|\bDIVERS\b',
   "Marine Services","Marine & offshore services"),
 (r'\bSHIPPING\b',"Shipping","Shipping & vessel services"),
 (r'\bFREIGHT\b|\bLOGISTICS\b|\bCARGO\b|\bCOURIER\b|\bSUPPLY CHAIN\b',
   "Logistics & Supply Chain","Freight forwarding & logistics"),
 (r'\bPORTS?\b|\bTERMINAL\b',"Ports & Terminals","Port operations"),
 (r'\bLIMOUSINE\b|\bPASSENGER TRANSPORT\b|\bCARS? & BUSES\b|\bBUS ',
   "Passenger Transport","Passenger & chauffeur transport"),
 (r'\bTRANSPORT(ING|ATION)?\b|\bTRUCKS?\b',
   "Freight Transport","Road transport & haulage"),
 (r'\bAVIATION\b|\bAIRLINE|\bAIR ?WING\b|\bAIRSERVICE',
   "Aviation","Aviation services"),

 # --- construction & built environment ---
 (r'\bSCAFFOLD',"Construction Services","Scaffolding & access"),
 (r'\bELECTRO ?MECHANICAL\b|\bELECTROMECHANICAL\b|\bELECT?RO MECH',
   "MEP & Electromechanical","MEP contracting & services"),
 (r'\bBUILDING (MATERIALS?|MATERIAL)\b|\bBLDG MATERIAL|\bHOUSE MATERIAL\b|\bSANITARY ?WARES?\b|\bSANITARYWARE\b|\bTILES\b|\bCERAMIC',
   "Building Materials Trading","Building materials & sanitaryware"),
 (r'\bCONTRACTING\b|\bCONTRACTORS?\b|\bCONSTRUCTIONS?\b|\bBUILDERS?\b|\bCONT\b|\bFOUNDATIONS\b|\bPRECAST\b',
   "Construction & Contracting","Building & civil contracting"),
 (r'\bLANDSCAP|\bIRRIGATION\b','Landscaping','Landscaping & irrigation'),
 (r'\bJOINERY\b|\bCARPENTRY\b|\bFIT ?OUT\b|\bFITOUT\b|\bINTERIOR|\bINTERIORS\b|\bDECOR',
   "Fit-Out & Joinery","Interiors, fit-out & joinery"),
 (r'\bFURNITURE\b|\bFURNISHING',"Furniture & Interiors","Furniture & furnishings"),
 (r'\bELEVATORS?\b|\bESCALATORS?\b',"Elevators & Escalators","Lifts & escalators"),
 (r'\bREAL ESTATE\b|\bPROPERT(Y|IES)\b|\bESTATES\b',"Real Estate","Property development & services"),
 (r'\bFACILIT(Y|IES) MANAGEMENT\b|\bCLEANING\b|\bBUILDING MAINTENANCE\b|\bGENERAL MAINTENANCE\b',
   "Facilities Management","FM, cleaning & maintenance"),
 (r'\bQUARR(Y|IES)\b|\bMINING\b',"Mining & Quarrying","Aggregates & minerals"),

 # --- manufacturing & industry ---
 (r'\bSWITCHGEAR\b',"Manufacturing - Electrical","Switchgear & panels"),
 (r'\bSTEEL\b|\bIRON\b|\bALUMINI?UM\b|\bMETALS?\b|\bCOPPER\b|\bFABRICATION\b|\bGALVANI',
   "Manufacturing - Metals","Metals & fabrication"),
 (r'\bPLASTICS?\b|\bPOLYMER|\bFIBERGLASS\b|\bFIBREGLASS\b|\bPLAS\b',
   "Manufacturing - Plastics","Plastics & polymers"),
 (r'\bPAPER\b|\bPACKAGING\b|\bPACKING\b|\bPACK\b|\bWIPES\b|\bCANS\b|\bPALLET',
   "Manufacturing - Paper & Packaging","Paper, packaging & disposables"),
 (r'\bCHEMICALS?\b|\bLUBRICANTS?\b|\bSILICONE\b|\bGASES\b',
   "Manufacturing - Chemicals","Chemicals & lubricants"),
 (r'\bPERFUMES?\b|\bCOSMETICS?\b|\bBEAUTY\b',
   "Cosmetics & Personal Care","Perfumes, cosmetics & beauty"),
 (r'\bGARMENTS?\b|\bTEXTILES?\b|\bFABRICS?\b|\bLINEN\b|\bSEWING\b|\bABAYA\b|\bREADYMADE\b|\bSHOES\b|\bFOOTWEAR\b|\bFASHION\b',
   "Textiles & Apparel","Textiles, garments & footwear"),
 (r'\bJEWEL|\bGOLD\b|\bGEMS\b|\bDIAMOND',"Jewellery & Precious Metals","Gold, jewellery & precious metals"),
 (r'\bWATCH(ES)?\b',"Luxury Retail","Watches & luxury goods"),
 (r'\bFACTORY\b|\bMANUFACTURING\b|\bMANUF\b|\bINDUSTR(Y|IES|IAL)\b|\bMFG\b|\bPRODUCTION\b',
   "Manufacturing","Industrial manufacturing"),

 # --- MEP / electrical / HVAC ---
 (r'\bAIR ?CONDITION|\bREFRIGERATION\b|\bHVAC\b|\bCOOLING\b|\bVENTILATION\b|\bDUCT',
   "HVAC","Air conditioning & refrigeration"),
 (r'\bELECTRICAL?S?\b|\bELECTRIC\b|\bLIGHTING\b|\bLIGHTS?\b|\bPOWER\b',
   "Electrical Trading","Electrical products & services"),
 (r'\bELECTRONICS?\b',"Consumer Electronics","Electronics distribution"),
 (r'\bWATER\b',"Water Treatment","Water systems & treatment"),

 # --- health ---
 (r'\bHOSPITAL\b|\bMEDICAL CENTER\b|\bMEDICAL CENTRE\b|\bCLINIC|\bHEALTH ?CARE\b|\bHEALTHCARE\b|\bDENTAL\b|\bIVF\b|\bTHERAP',
   "Healthcare","Clinics, hospitals & health services"),
 (r'\bPHARMACY\b',"Pharmacy Retail","Community pharmacy"),
 (r'\bPHARMA|\bDRUG STORE\b|\bMEDICINES?\b',"Pharmaceuticals","Pharmaceutical distribution"),
 (r'\bMEDICAL\b|\bSURGICAL|\bDIAGNOSTIC|\bBIOTECH|\bBIO ',
   "Medical Supplies","Medical equipment & supplies"),
 (r'\bOPTICAL\b',"Retail","Optical & eyewear retail"),

 # --- services ---
 (r'\bRECRUITMENT\b|\bMANPOWER\b|\bLABOR SUPPLY\b|\bLABOUR SUPPLY\b|\bEMPLOYMENT\b|\bOUTSOURCING\b|\bHR\b|\bWORKFORCE\b',
   "HR & Recruitment","Recruitment & manpower"),
 (r'\bSECURITY\b',"Security Services","Security services & systems"),
 (r'\bINSURANCE\b',"Insurance Services","Insurance & broking"),
 (r'\bBANK\b|\bEXCHANGE\b|\bFINANCIAL\b|\bFINCORP\b|\bCAPITAL\b',
   "Financial Services","Financial services"),
 (r'\bSCHOOL\b|\bACADEMY\b|\bEDUCATION\b|\bTRAINING\b|\bINSTITUTE\b|\bUNIVERSITY\b',
   "Education","Schools & training"),
 (r'\bHOTEL\b|\bRESORT\b|\bHOSPITALIT',"Hospitality","Hotels & hospitality"),
 (r'\bTOURISM\b|\bTRAVEL\b',"Travel & Tourism","Travel services"),
 (r'\bADVERTISING\b|\bMARKETING\b|\bMEDIA\b|\bBRANDING\b',"Marketing Services","Advertising & marketing"),
 (r'\bEVENTS?\b|\bEXHIBITION',"Events & Exhibitions","Events & exhibitions"),
 (r'\bENTERTAINMENT\b|\bLEISURE\b|\bTHEME PARK\b|\bGYM\b|\bFITNESS\b',
   "Entertainment & Leisure","Leisure & entertainment"),
 (r'\bLAUNDRY\b',"Laundry Services","Commercial laundry"),
 (r'\bWASTE\b|\bRECYCLING\b',"Recycling & Waste","Waste management"),
 (r'\bSOFTWARE\b|\bIT SOLUTIONS?\b|\bINFORMATION TECHNOLOG|\bCOMPUTER\b|\bDATA\b|\bDIGITAL\b|\bWEB\b',
   "IT Services","IT & software services"),
 (r'\bTELECOM|\bCOMMUNICATIONS?\b',"Telecommunications","Telecom services & equipment"),
 (r'\bCONSULT(ING|ANCY|ANT|ANTS)?\b|\bADVISORY\b|\bAUDITORS?\b|\bACCOUNTANTS?\b',
   "Professional Services","Consulting & advisory"),
 (r'\bTECHNICAL SERVICES?\b|\bTECHNICAL WORKS?\b',"Technical Services","Technical & maintenance services"),
 (r'\bENGINEERING\b|\bENGINEERS?\b',"Engineering Services","Engineering services"),
 (r'\bRENTAL\b|\bRENT\b|\bLEASING\b',"Equipment Rental","Rental services"),
 (r'\bAGRICULTURE\b|\bAGRI\b|\bFARM\b',"Agriculture","Agriculture & agri-inputs"),
 (r'\bFLOWERS?\b|\bFLORA\b',"Florist & Gifts","Flowers & gifts"),
 (r'\bHEAVY EQUIPMENT\b|\bCRANES?\b|\bLIFTING\b|\bMACHINERY\b|\bEQUIPMENT\b',
   "Industrial Equipment","Industrial & heavy equipment"),
 (r'\bHARDWARE\b|\bBEARINGS\b|\bVALVES?\b|\bPIPES?\b|\bPIPE\b|\bFILTERS?\b|\bHYDRAULIC',
   "Industrial Distribution","Industrial products distribution"),
 (r'\bRETAIL\b|\bMALL\b|\bBOUTIQUE\b|\bDEPARTMENT STORE\b|\bSTATIONERY\b',
   "Retail","Retail operations"),
 (r'\bINVESTMENTS?\b|\bHOLDING\b',"Investment & Holding","Investment & holding"),
 (r'\bGROUP\b',"Diversified Group","Diversified group"),
 (r'\bDISTRIBUTION\b|\bDISTRIBUTORS?\b',"Distribution","Wholesale distribution"),
 (r'\bTRADING\b|\bTRADERS?\b|\bTRADE\b|\bTRD\b|\bENTERPRISES?\b|\bSUPPLY\b|\bSUPPLIES\b|\bIMPEX\b',
   "Trading & Distribution","General trading & wholesale"),
 (r'\bTECHNOLOG(Y|IES)\b|\bTECH\b|\bSOLUTIONS?\b|\bSYSTEMS?\b',
   "Technology","Technology products & solutions"),
 (r'\bSERVICES?\b',"Services","General services"),
]
COMPILED = [(re.compile(p), a, b) for p, a, b in RULES]

from verified import VERIFIED
VERIFIED_N = {norm(k): v for k, v in VERIFIED.items()}
OVERRIDES.update(VERIFIED)
OVERRIDES = {norm(k): v for k, v in OVERRIDES.items()}

def classify(name):
    n = norm(name)
    src = "Web-verified" if n in VERIFIED_N else "Name-derived"
    if n in OVERRIDES:
        i, s2, c = OVERRIDES[n]
        return (i, s2, c, src)
    for rx, ind, sub in COMPILED:
        if rx.search(n):
            return (ind, sub, "Medium", src)
    return ("Unclassified", "No industry signal in the name", "Low", src)

lines = [l.rstrip('\n') for l in open('all_lines.txt', encoding='utf-8') if l.strip()]

# per-unique-name lookup table
seen = {}
for l in lines:
    seen.setdefault(l, 0)
    seen[l] += 1

with open('company_industry_lookup.csv','w',newline='',encoding='utf-8-sig') as f:
    w = csv.writer(f)
    w.writerow(['Company Name','Industry','Sub-Industry / Activity','Confidence','Source','Rows in source list'])
    for nm in sorted(seen, key=lambda s: norm(s)):
        ind, sub, conf, src = classify(nm)
        w.writerow([nm, ind, sub, conf, src, seen[nm]])

# full list in original order
with open('company_industry_full_list.csv','w',newline='',encoding='utf-8-sig') as f:
    w = csv.writer(f)
    w.writerow(['Column1.PARTYMST_DESC','Industry','Sub-Industry / Activity','Confidence','Source'])
    for l in lines:
        ind, sub, conf, src = classify(l)
        w.writerow([l, ind, sub, conf, src])

from collections import Counter
c = Counter(classify(nm)[0] for nm in seen)
print("unique companies:", len(seen), "| total rows:", len(lines))
print("\n--- industry spread (unique companies) ---")
for k,v in c.most_common():
    print(f"{v:5d}  {k}")
