# Web-verified classifications (searched individually, Sept 2026)
VERIFIED = {
 "ROLMAN WORLD FZE": ("Industrial Distribution","Bearings, power transmission & auto/industrial spare parts (NSK master distributor)","High"),
 "KLEEV MIDDLE EAST FZE": ("Manufacturing - Instrumentation","Instrumentation valves, manifolds, gauges & thermocouples","High"),
 "BDH MIDDLE EAST LLC": ("Laboratory Supplies","Lab chemicals, glassware, instruments & lab fit-out","High"),
 "DYNAMICNORD MIDDLE EAST ASIA & AFRICA FZE": ("Sports & Outdoor Equipment","Diving, swimming & watersports gear (DynamicNord brand)","High"),
 "ILG EMEA DWC LLC": ("Trading & Distribution","Watches, jewellery, leather goods & optical products trading","Medium"),
 "YKM MIDDLE EAST L.L.C.": ("Manufacturing - Metals","Wire mesh, chain link fencing & shade nets","High"),
 "RME MIDDLE EAST FZCO": ("Industrial Distribution","Welding consumables & CNC / steel fabrication equipment (Rywal-RHC)","High"),
 "STERLING SITES FZCO": ("Building Materials Trading","Ladders, adhesives, abrasives, hardware & sanitaryware","High"),
 "VALCROM GLOBAL DWC LLC": ("Industrial Distribution","Valves, actuators, pipes, flanges & gaskets for oil, gas & water","High"),
 "TRI STAR GULF FZCO": ("Building Materials Trading","Building & interiors products trading","Low"),
 "MECHWAY GLOBAL LLC": ("Industrial Distribution","Mechanical components for building services & infrastructure","Medium"),
 "PROCON EMIRATES LLC": ("Construction Services","Fireproofing & surface protection contracting (Muehlhan Group)","High"),
 "GOLDEN RELIEF RESOURCES L.L.C": ("Construction & Contracting","Construction, equipment leasing & procurement services","High"),
 "AMC INTERNATIONAL DMCC": ("Distribution","FMCG sourcing & distribution into West Africa","High"),
 "ORIENT LINKS CO. LLC": ("Paper & Packaging Trading","Paper, board & tissue trading across MEA","High"),
 "TRITON MIDDLE EAST LLC": ("Manufacturing - Chemicals","Sealants, waterproofing & protective coatings","High"),
 "LINK MIDDLE EAST FZE": ("Manufacturing - Metals","Galvanized wire, perimeter fencing, gabions & guard rails","High"),
 "PRIME MIDDLE EAST FZE": ("Manufacturing - Chemicals","Industrial, refrigerant, medical & LPG gases","High"),
 "METRO INTERNATIONAL LLC": ("Manufacturing - Paper & Packaging","Drum/can closures, packaging components & filtration","High"),
 "GREAT PACIFIC LLC": ("Steel & Metals Trading","Steel, raw materials, minerals & petrochemicals trading","High"),
 "PROTRADE INTERNATIONAL UAE": ("Trading & Distribution","Master distributor - tools, electrical, plumbing, HVAC & building materials","High"),
 "TERZETTO OVERSEAS DMCC": ("Timber & Wood Trading","Hardwood & teak timber trading (Terzetto Group)","High"),
 "TERZETTO": ("Timber & Wood Trading","Hardwood & teak timber trading (Terzetto Group)","Medium"),
 "RSG GLOBAL LLC": ("Cold Storage & Warehousing","Temperature-controlled / frozen foodstuff warehousing","High"),
 "SAIGOL & GULF LIMITED COMPANY LLC": ("Food & Beverage Trading","Snacks, crisps, biscuits & rice distribution","High"),
 "BORG ROLLS WARNER MIDDLE EAST LLC": ("Automotive Parts Trading","Aftermarket spare parts for European trucks & heavy equipment","High"),
 "ELEVATE GLOBAL FZE": ("Events & Exhibitions","Event staffing & brand activation","Medium"),
 "VIVENTUM INTERNATIONAL W.L.L": ("Pharmaceuticals","Pharma, medical device & FMCG distribution (Qatar)","High"),
 "DAS COLLECTION LLC": ("Textiles & Apparel","Luxury designer abayas & womenswear","High"),
 "WHITE LABEL L.L.C": ("Food Service","F&B / hospitality group (Billionaire Mansion, Epicure Catering, Cirque le Soir)","High"),
 "AAGT INTERNATIONAL LLC": ("Trading & Distribution","Procurement & sourcing / import-export","High"),
 "AAGT INTERNATIONAL SURPLUS STORE": ("Retail","Surplus & general goods retail","Medium"),
 "AL NAHDA INTERNATIONAL FZCO": ("Chemicals Distribution","Drilling-mud, detergent & personal care chemicals distribution","High"),
 "AL LOKRIT INTERNATIONAL LLC": ("Florist & Gifts","Cut flowers, plants, floral accessories & planters wholesale","High"),
 "GOLDEN ARENA UNITED LLC": ("Manufacturing - Building Products","Aluminium & glass fabrication and accessories (Oman)","High"),
 "TECHNICAL RESOURCES LLC": ("Industrial Equipment","Equipment sales, service, plant hire & workshops (Albwardy Group)","High"),
 "ABMAK QATAR WLL": ("Furniture & Interiors","Furniture, furnishings & flooring for homes, offices & schools","High"),
 "AG CORPORATION FZE": ("Fire & Safety","Safety equipment & PPE supply to oil & gas","High"),
 "FAKHREE CENTER L.L.C.": ("Retail","Imitation jewellery, cosmetics, fragrances & general goods wholesale","High"),
 "FAKHREE AL HINDI GROUP": ("Retail","Imitation jewellery, cosmetics, fragrances & general goods wholesale","High"),
 "S.K ALLIED INTERNATIOANL L.L,C": ("Retail","Food retail","Medium"),
 "MIX PARTS L. L. C.": ("Automotive Parts Trading","Auto spare parts trading (inferred - not found online)","Low"),
 # searched, nothing conclusive found
 "TIME BRIDGE FZCO": ("Unclassified","Searched - no public business description found","Low"),
 "DFC MIDDLE EAST LIMITED BRANCH": ("Unclassified","Searched - no public business description found","Low"),
 "ARDH AL RABIEE LLC": ("Unclassified","Searched - no public business description found","Low"),
}

# Inferred from a sibling entity that appears elsewhere in the same customer list
SIBLING = {
 "AL RAWABIT INTERNATIONAL L.L.C": ("HR & Recruitment","Inferred from sibling entity 'Al Rawabit International Recruitment LLC'","Medium"),
 "ABDUL HAMID ABEDI CO. (L.L.C)": ("Fresh Produce & Grocery","Inferred from sibling entity 'Gholami & Abedi Fruits & Vegetables Co.'","Low"),
 "ABDULLA AHMED ZAMINPIMA AWAZI CO LLC": ("Trading & Distribution","Inferred from sibling entity 'Abdulla Ahmed Al Awazi General Trading Co. LLC'","Low"),
 "AL HUMAIDI & CO LLC": ("Trading & Distribution","Inferred from sibling entity 'Al Humaidi Trading Enterprises LLC'","Low"),
}
VERIFIED.update(SIBLING)
